### ISSUE TITLE
네트워크, 인터넷, WWW 란?

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#10]

**Comment by dudupeng3105** [comment]
네트워크 - 노드(컴퓨터 혹은 통신장비)가 데이터를 공유할 수 있게 하는 전기통신망의 하나
인터넷 - 그림, 문서, 영상 여러 데이터를 공유하도록 구성된 네트워크
www - 웹과 관련된 데이터를 공유함

**Comment by kevin123488** [comment]
네트워크: 분산되어 있는 컴퓨터를 통신망으로 연결한 것
인터넷: 전세계를 연결하는 네트워크
www: 인터넷을 통해 웹과 관련된 데이터를 공유

**Comment by nuriring** [comment]
WWW : world wide web
네트워크 : 데이터 송수신 통로
인터넷 : 그림 문서 영상 여러 데이터를 공유하도록 구성된 전 세계를 연결하는 네트워크

**Comment by mouseJAVA777** [comment]
네트워크 : net + work -> 컴퓨터들이 통신 기술을 활용하여 그물망처럼 연결된 형태
인터넷 : 전세계를 잇는 컴퓨터 네트워크의 시스템
www :  world wide web -> 전세계에 퍼져있는 웹 구축망

**Comment by bds01088** [comment]
네트워크란 전자 통신망으로 여러 노드들이 정보를 주고 받을 수 있는 곳이다.
인터넷은 네트워크 중 하나이다.
www는 인터넷을 통한 웹통신의 규범화된 기술이다.

**Comment by CHOIJXWXN** [comment]
네트워크는 노드 간의 데이터를 공유할 수 있게 하는 통신망이고 인터넷은 그 중 하나이다.
WWW는 World Wide Web으로 인터넷 중에서도 웹과 관련된 데이터를 공유하는 일부를 의미한다.
