### ISSUE TITLE
TCP/IP와 OSI 7-Layer의 차이점을 얘기하시오

### ISSUE THREAD

**Issue by bds01088** [mouseJAVA777/class_md#13]

**Comment by dudupeng3105** [comment]
TCP/IP - 4계층, 네트워크 통신을 기술에 따라 분류함
OSI - 7계층, 데이터의 흐름을 논리적으로 구간별로 분류함

**Comment by ohhamin** [comment]
TCP/IP 4계층은 네트워크인터페이스(물리, 데이터링크) 네트워크(네트워크) 전송(전송) 응용(세션, 표현, 응용) / 괄호가 7계층
으로 나누어져 있다. 실제 네트워크는 TCP/IP 4계층에 가까움

**Comment by kevin123488** [comment]
OSI는 역할 기반, TCP/IP는 프로토콜 기반 // OSI는 통신 전반에 대한 표준, TCP/IP는 데이터 전송기술 특화

**Comment by CHOIJXWXN** [comment]
TCP/IP는 4계층으로 나누어져있으며 실무적인 느낌이 강하고 OSI는 7계층으로 나누어져있으며 논리적인 느낌이 강하다.

**Comment by mouseJAVA777** [comment]
TCP/IP는 4계층으로 이루어져있고, -> 프로토콜 기반
OSI는 7계층으로 이루어져 있음 -> 역할 기반
