### ISSUE TITLE
2계층 프로토콜의 구성은?

### ISSUE THREAD

**Issue by bds01088** [mouseJAVA777/class_md#14]
수신 주소, 송신 주소, 이더넷타입, 페이로드

**Comment by ohhamin** [comment]
수신 어드레스, 송신 어드레스, 이더넷타입

**Comment by nuriring** [comment]
수신, 송신 , 이더넷 타입

**Comment by dudupeng3105** [comment]
destination, source, Ethernet type

**Comment by CHOIJXWXN** [comment]
Destination Address, Source Address, Ethernet Type

**Comment by kevin123488** [comment]
Destination Address + Source Address + Ethernet Type

**Comment by mouseJAVA777** [comment]
도착지 맥주소 + 송신지 맥주소 + 이더넷 타입
