### ISSUE TITLE
눌관식

### ISSUE THREAD

**Issue by nuriring** [mouseJAVA777/class_md#15]
데이터에 TCP 만 붙어있는 형태의 4계층 PDU(Protocol Data Unit)를 부르는 또 다른 말은 무엇인가

​   (1). 세그먼트

​   (2). 패킷

​   (3). 프레임

**Comment by ohhamin** [comment]
1

**Comment by bds01088** [comment]
1

**Comment by dudupeng3105** [comment]
1

**Comment by CHOIJXWXN** [comment]
1

**Comment by kevin123488** [comment]
1

**Comment by mouseJAVA777** [comment]
데이터에 TCP 만 붙어있는 형태의 4계층 PDU(Protocol Data Unit)를 부르는 또 다른 말은 1번 세그먼트 입니다.
