### ISSUE TITLE
네트워크 통신방식(유니캐스트, 멀티캐스트, 브로드캐스트) 에 대해 설명하시오.

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#17]

**Comment by CHOIJXWXN** [comment]
유니 캐스트는 1대1
멀티 캐스트는 1대N (특정 다수)
브로드 캐스트는 1대N (불특정 다수)

**Comment by nuriring** [comment]
유니캐스트는 1대1
멀티 캐스트는 1대다
브로드 캐스트도 1대다 - 불특정

**Comment by bds01088** [comment]
유니 = 1:1
멀티 = 1 : 부분집단
브로드 = 1 : 네트워크 내 전체

**Comment by mouseJAVA777** [comment]
유니캐스트 : 강사님이 혜라에게만 말함 
멀티 캐스트: 강사님이 여러명에게 말함
브로드 캐스트 : 강사님이 반 전체에게 말함

**Comment by dudupeng3105** [comment]
위 의견들에 동의합니다.
