### ISSUE TITLE
사설 ip와 공인 ip의 개념에 대해 간단히 설명하시오

### ISSUE THREAD

**Issue by kevin123488** [mouseJAVA777/class_md#18]

**Comment by bds01088** [comment]
사설 IP는 lan과 같은 개념으로 하나의 공유기에 포함되어있는 IP들이고
공인 IP는 인터넷이나 다른 네트워크와 데이터를 주고 받을 때 사설 IP가 변환되어 하나의 통일된 IP이다

**Comment by ohhamin** [comment]
점점 전자기기가 많아짐에 따라 네트워크 주소가 또 부족해졌다. 그래서 하나의 공인 IP 안에 여러개의 사설 IP를 사용하여 사설 IP에서 외부 네트워크 대역과 통신을 할 때 공인 IP 주소로 바꾸어 통신한다.

**Comment by dudupeng3105** [comment]
공인 IP는 인터넷에 접속하려면 필요한 IP로 전세계에서 유일 해야 하는 식별자 이다. 사설 IP는 하나의 공인 IP 네트워크 대역 안에 다수의 기기들이 사설 IP를 사용해서 IP 주소의 부족을 해결했고, 이 때 사설 IP는 NAT  기술을 사용하여 사설 IP -> 공인 IP로 인터넷에 접속 할 수 있다.

**Comment by nuriring** [comment]
사설 IP는 ipconfig를 통해 확인 할 수 있는 고유한 IP주소이며, 외부에서는 보이지 않는다. 공인 IP는 사설 IP 주소의 응답을 내보내는 게이트웨이로서 하나의 공유기마다 공인 IP를 통해 외부로 통신이 가능하다.

**Comment by mouseJAVA777** [comment]
공인 IP 주소 : 실제 다른 컴퓨터와 통신할 때 쓰이는 IP주소, IP주소를 관리하는 기관에서 할당해줌 
사설 IP 주소 : 공유기 또는 VPN장비를 통해 각 장비에 부여된 IP 주소

**Comment by wns0394** [comment]
사설 IP는 같은 네트워크 대역에서 사용하는것이고 공인 IP는 실제로 다른 컴퓨터와 통신할 때 사용
