### ISSUE TITLE
a가 c와 통신을 하고 싶다고 한다. arp 요청 프로토콜을 만드는 데, 목적지의 mac 주소를 몰라 arp 프로토콜의 destination hadware address 부분을 올바르게 채울 수 없다. 이 때 어떻게 해당 부분을 채워 보내는가?

### ISSUE THREAD

**Issue by kevin123488** [mouseJAVA777/class_md#19]

**Comment by dudupeng3105** [comment]
6바이트 모두 0으로 채운다. 그리고 2레벨 이더넷 헤더에서는 목적지 mac 주소를 F로 6바이트 채워서 broadcast 통신임을 스위치에게 알려줄 수 있다.

**Comment by ohhamin** [comment]
ARP 프로토콜의 목적지 MAC 주소는 0으로 채우고 2계층인 이더넷 프로토콜에는 목적지 MAC 주소에 F로 채워 브로트캐스팅 하여 모든 기기에 전달하게 한다.

**Comment by bds01088** [comment]
목적지 주소에는 0으로 채우고 이더넷 프로토콜에 목적지는 F로 채워 브로드캐스팅인걸 알려서 모두에게 전파한다.

**Comment by nuriring** [comment]
해당 부분은 0으로만 채우고 이더넷 주소는 F 로만 채워서 보내서 브로드캐스트 방식으로 모두에게 통신하면, 목적지와 출발지의 IP 주소가 일치할 때 목적지의 MAC주소를 알아올 수 있다.

**Comment by wns0394** [comment]
MAC주소를 모르므로 00 00 00 00으로 넣고  목적지 주소는 아니까 F로 채운다

**Comment by mouseJAVA777** [comment]
목적지 mac은 0으로 채움 
브로드캐스트 방식으로 통신하기 위해 이더넷은 F로 채움
