### ISSUE TITLE
TCP, HTTP, IPv4 Ethernet 프로토콜을 모두 이용한 패킷을 만들어 통신을 하려고 한다. 이 때 패킷을 만드는 과정(캡슐화)에 대해 설명하라

### ISSUE THREAD

**Issue by dudupeng3105** [mouseJAVA777/class_md#2]

**Comment by kevin123488** [comment]
페이로드에 HTTP라는 헤더를 붙임 -> 그 패킷을 하나의 페이로드로 해서 TCP라는 헤더를 붙임 -> 그 패킷을 하나의 페이로드로 해서 IPv4라는 헤더를 붙임 -> 그 패킷을 하나의 페이로드로 해서 Ethernet이라는 헤더를 붙임

**Comment by bds01088** [comment]
데이터에 해더를 붙이는데 tcp http ipv4 이더넷 순으로 붙인다

**Comment by bds01088** [comment]
데이터에 해더를 붙이는데 tcp http ipv4 이더넷 순으로 붙인다

**Comment by CHOIJXWXN** [comment]
전송하고자하는 데이터에 HTTP를 붙여 하나의 패킷을 만든 후, 해당 패킷을 페이로드로 하고 TCP를 헤더로 하는 패킷을 만든다. 그리고 그 패킷을 페이로드로 하고 IPv4를 헤더로 하는 패킷을 만들고 해당 패킷을 페이로드로 하고 Ethernet을 헤더로 하는 패킷을 만들어 캡슐화를 진행한다.

**Comment by nuriring** [comment]
캡슐화는 데이터를 보낼 때 하위계층에서 상위계층으로 데이터를 전송하는 과정이다. tcp 를 헤더 http를  페이로드에 담아서 상위계층으로 전달하면 하나의 페이로드가 되고 이 페이로드에 또다시 헤더를 붙여서 캡슐화를 진행한다

**Comment by mouseJAVA777** [comment]
HTTP + 데이터 
                              TCP + (HTTP + 데이터) 
                   IPv4 + (TCP + HTTP + 데이터)
 ethernet + (IPv4 + TCP + HTTP + 데이터 )
 
 데이터를 하위계층에서 상위 계층으로 전달할 때, 여러 프로토콜들로 캡슐화된 패킷을 전달하고, 다음 계층에서 새로운 헤더를 앞에 붙이는 식으로 진행됨.

**Comment by ohhamin** [comment]
페이로드가 있고 그 페이로드의 헤더를 붙이고 그게 다음 통신에서 페이로드가 되고 하는 식으로 포장지를 싸는 것 처럼 캡슐화를 진행한다. 캡슐화를 진행하는데 전보다 더 높은 계층은 쓸 수 없다.

**Comment by hula-la** [comment]
상위계층에서 하위계층으로 내려가면서 헤더를 추가하여 전달하고, 하위계층에선 상위계층에서 전달한 패킷을 페이로드로 받는다. 순서는 http(응용) -> tcp (전송) -> IPv4(인터넷) -> ethernet (링크)
