### ISSUE TITLE
서브넷 마스크란?

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#20]

**Comment by kevin123488** [comment]
IP 주소에 대한 네트워크의 대역을 규정하는 것

**Comment by dudupeng3105** [comment]
IP 주소의 네트워크 주소 영역과 호스트 주소 영역을 구분해준다. 1과 0의 경계에서 그 두 부분이 구분된다.

**Comment by bds01088** [comment]
클래스풀한 IP는 너무 많은 IP 주소를 낭비하므로 유연한 네트워크대역의 설정을 위해 사용되는 것이 서브넷 마스크이다.
서브넷 마스크는 2진수로 변경했을때 1로 시작하며 IP주소에서 네트워크 대역의 구분으로 사용될 범위만큼만 서브넷마스크에서 1로 채워주고 이후 사용자의 실질 ip를 구분하는 위치에는 0을 입력해줌으로써 다양한 네트워크 대역에 적절한 ip주소 크기를 사용할 수 있게 해준다.

**Comment by nuriring** [comment]
서브넷 마스크는 classless한 IP 주소 분류방식에서, 4바이트 식 필드 별로 클래스를 구분하는 것이 아니라, IP의 낭비를 방지하기 위해 서브넷 마스크의 1에 해당하는 부분을 네트워크 대역, 0애 해당하는 부분을 해당 네트워크에서 관리하는 컴퓨터의 수로 활용할 수 있게 하여, 원하는 임의의 필드 범위로 끊어서 사용할 수 있다.

**Comment by wns0394** [comment]
네트워크주소 부분과 호스트 주소 부분을 구별해준다 1하고 0이 바뀌는 그 부분 앞으로는 네트워크 부분 뒤로는 호스트 부분

**Comment by mouseJAVA777** [comment]
0의 부분은 호스트, 1의 부분은 네트워크 부분을 나타내어 IP주소를 네트워크 및 호스트 주소로 분리한다.
