### ISSUE TITLE
IP와 서브넷마스크

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#21]
9. IP는 13x.xxx.xx.132  서브넷 마스크는 255.255.255.192이다. 해당 네트워크 주소와 브로드캐스트 주소를 제외한 호스트 개수는?
해당 네트워크 주소 : 
브로드캐스트 주소 : 
[출처] [22년 2회 정보처리기사 실기 문제]

**Comment by ohhamin** [comment]
62?

**Comment by dudupeng3105** [comment]
192 = 11 000000 => 서브넷이 가질 수 있는 최대 ip 개수 2^6 = 64개, 그 중 첫 번째 숫자는 네트워크 주소를, 마지막 숫자는 브로드캐스트 주소를 가리킴 현재 ip가 132 이므로 128~191 범위에 있는 것임 따라서
네트워크 주소: 13x.xxx.xxx.128
브로드캐스트 주소: 13x.xxx.xxx.191

**Comment by bds01088** [comment]
아잇 2진수 변환해서 문제내줘요
192 : 11000000 이므로 맨뒤에서 6번째 자리까지만 ip의 개수이다.
2^6이므로 64개인데
가장 작고 가장 큰 두 개의 ip는 네트워크 주소와 브로드캐스트 주소로 쓰인다.
그러므로 총 62개의 ip주소를 가짐
132 : 10000100 이므로 10 000000 ~ 10 111111이다 
10 000000 : 128
10 111111 : 191
네트워크 주소 : ~~~.128
브로드캐스트 주소 : ~~~.191

**Comment by nuriring** [comment]
잘 모르겠다요...ㅜ

**Comment by mouseJAVA777** [comment]
문제는 나도 이해못해서 낸거임 엌
