### ISSUE TITLE
ipv4에서 주소뿐만 아니라 서브넷 마스크도 필요하다 이유를 설명하시오

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#22]

**Comment by dudupeng3105** [comment]
네트워크 주소 영역과 호스트 주소 영역을 구분하기 위해서

**Comment by nuriring** [comment]
서브넷 마스크가 있어야 네트워크 대역과, 해당 네트워크에서 통신하는 컴퓨터 대역에 대한 필드를 구분해서 IP 주소의 낭비없이 사용이 가능합니다.

**Comment by bds01088** [comment]
옛날 classful한 ip주소에서는 서브넷 마스크가 필요없었지만
현대에는 ip 주소가 부족하므로 비효율적인 classful한 분류 대신 classless한 분류를 사용하기 위해서 서브넷마스크가 꼭 필요하다

**Comment by mouseJAVA777** [comment]
[bds01088]에게 동의합니다

**Comment by kevin123488** [comment]
컴퓨터 사용 인구가 많아져서 기존 방식으로는 ip 할당 불가 -> 서브넷 마스크를 이용하여 classless한 분류를 이용 -> 가능해짐
