### ISSUE TITLE
ARP 동작 순서를 간단하게 설명하시오

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#23]

**Comment by ohhamin** [comment]
1. ARP 요청 캡슐화(ARP에서 MAC 주소를 0으로 채우고 이더넷에서 목적지 MAC 주소를 F로 채워 브로드캐스트)
2. 2계층 장비에서 2계층 프로토콜(이더넷) 확인 후 모두에게 보냄
3. 받은 장비들이 디캡슐레이션 하여 내 IP주소와 목적지 IP주소가 같은지 확인
4. 내 IP주소와 같다면 응답 ARP 프로토콜을 만들어 출발 MAC주소엔 내 MAC주소, 도착 MAC주소엔 요청 온 MAC 주소로 보냄
5. 요청 보낸 쪽에서 응답 ARP 프로토콜을 받아 ARP 캐시 테이블에 IP주소와 MAC 주소 저장

**Comment by dudupeng3105** [comment]
1. ARP 요청 캡슐화(ARP에서 목적지 mac주소를 0(6바이트)로 채우고, 이더넷 헤더의 목적지 MAC 주소를 F로 채워 브로드캐스트)
2. 2레벨 장비 스위치에서 2계층을 까보고 브로드캐스트인 것을 확인 같은 네트워크 대역의 모든 기기에 보냄
3. 받은 기기들이 3계층을 디캡슐레이션하고 목적지 IP주소가 자신의 기기와 다르면 버리고 같으면 응답 ARP를 만들어 보내는 데 이 때는 출발, 목적 MAC 주소를 모두 아는 상태임(사실상 유니캐스트임 이때는) 그래서 이렇게 ARP 통신을 보내고
4. 스위치에서는 이제 목적지 맥 주소를 알고 있으므로 바로 목적지 기기에 보냄
5. 목적지 기기에서 ARP 프로토콜을 받아 ARP 캐시 테이블에 IP주소와 MAC 주소 저장 후 원하는 통신을 수행함(유니캐스트로)

**Comment by nuriring** [comment]
1. 이더넷은 F로 채우고 , 목적지 MAC주소는 0으로 채워서 브로드캐스트 방식으로 ARP 요청을 보낸다.
2. 브로드 캐스트 방식으로 모두에게 보내면 IP 주소가 일치하는 패킷만 살아남는다.
3. IP 주소가 일치하는 경우 목적지의 MAC주소를 담아서 출발지 MAC주소로 ARP 응답을 보낸다
4. 출발지 맥주소에서 ARP 응답을 받으면 MAC 주소를 ARP 테이블에 기록한다.

**Comment by bds01088** [comment]
1. APR 요청 작성
2. 모두에게 보냄
3. 일치하는 MAC주소를 가진 장비가 응답을 보냄
4. 응답이기 때문에 받은 장비는 답을 보내야할 MAC주소를 알고 있음
5. 자신의 MAC주소를 담아서 보냄

**Comment by mouseJAVA777** [comment]
송신자가 목적지 IP 로 패킷 송신
IP 프로토콜이 ARP 프로토콜에게 ARP 메시지 생성 요청
메시지 encapsulation
모든 수신자 중 일치하는 주소를 가진 장비는 응답 
해당 장비가 자신의 물리 주소를 포함한 arp reply 송신 
최초 송신측에 목적지 물리주소 정보 도달

**Comment by kevin123488** [comment]
목적지의 mac 주소를 모르는 상황 -> 이더넷 프로토콜의 목적지 mac 주소 부분을 1로 채움 -> 모두에게 전송 -> ip주소를 비교 -> 일치하는 경우 ARP 응답을 보냄
