### ISSUE TITLE
classful IP주소와 classfulless IP주소의 차이점을 classful IP 주소가 잘 쓰이지 않게 된 이유를 중심으로 서술하시오

### ISSUE THREAD

**Issue by nuriring** [mouseJAVA777/class_md#24]

**Comment by ohhamin** [comment]
classful IP 주소는 네트워크 대역을 A클래스, B클래스와 같이 너무 크게 나누기 때문에 낭비되는 주소가 너무 많아진다. 전자장비가 많아짐에 따라 주소가 부족하게 되었고, 서브넷마스크를 통해 유동적으로 네트워크 대역을 설정하는 classfulless IP 주소가 쓰이게 되었다.

**Comment by dudupeng3105** [comment]
classful 주소는 A, B, C, D, E로 나누는 데 사실 클래스를 알맞게 쓰면 큰 문제가 없었겠지만, 대다수의 큰 기관들이나 작은 회사라도 미래를 생각해서, 호스트 주소가 많은 A 클래스를 쓰는 경우가 많았음 그래서 결국 B, C 클래스 주소의 낭비가 생겼고, 그와 함께 통신 장비가 많아지면서 주소가 부족해짐 그래서 서브넷마스크를 통해 네트워크-호스트 구분 기준을 사용자가 정해 원래 단위보다 쪼개어 사용하는 것이 classfulless ip의 큰 특징이다.

**Comment by wns0394** [comment]
classfulless ip주소는 자기가 원하는 곳에서 잘라서 사용하기 때문에 주소 낭비가 없다. 반면 classful ip주소는 지정된 크기에 잘라서 주소가 부족해져서 사용하지 않게 되었다

**Comment by bds01088** [comment]
classful IP 주소를 사용할 당시에는 네트워크에 접속하는 장비들이 많이없어서 낭비를 해도 되었지만
현대에 와서는 많은 네트워크 이용자들이 존재하기때문에 ip주소의 낭비를 최소화하기 위해서 classless한 ip주소를 사용하도록 바뀌었다.

**Comment by mouseJAVA777** [comment]
세상에 IP주소가 많아져서 낭비하는 주소가 있으면 IP주소가 모잘라게 되었다

**Comment by kevin123488** [comment]
classful ip는 낭비하는 ip주소가 많음. classless ip를 이용하여 ip주소 낭비를 최소화
