### ISSUE TITLE
ARP 프로토콜에서 목적지의 mac 주소를 알 수 없을 때 이터넷 프로토콜이 인캡슐레이션 하는 방식을 서술하시오

### ISSUE THREAD

**Issue by nuriring** [mouseJAVA777/class_md#25]

**Comment by ohhamin** [comment]
ARP 프로토콜의 도착지 MAC 주소는 0으로 채우고 2계층인 이더넷 프로토콜의 도착지 MAC 주소는 F로 채워 브로드캐스팅하여 모든 전자기기에 프로토콜을 보낸다.

**Comment by dudupeng3105** [comment]
3계층 ARP 프로토콜에서는 목적지 맥주소를 6바이트 모두 0으로 채운다. 그리고 2레벨 이더넷 헤더에서는 목적지 mac 주소를 F로 6바이트 채워서 broadcast 통신임을 스위치에게 알려줄 수 있다.

**Comment by kevin123488** [comment]
목적지 mac 주소 1로 가득 채움(FF FF FF FF FF FF) -> boradcast(모두에게 보냄)

**Comment by bds01088** [comment]
arp 프로토콜의 도착 mac주소는 0으로 채우고, 이더넷 프로토콜의 도착 MAC주소는 F로 가득 채워 브로드 캐스팅한다.

**Comment by wns0394** [comment]
목적지 mac주소를 모르니까 00 00 00 00으로 넣고 보낸다

**Comment by kevin123488** [comment]
목적지 mac주소를 모르기 때문에 1으로 채워서 보냄
