### ISSUE TITLE
ARP와 RARP에 대해 아는대로 설명하라

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#26]
ARP와 RARP에 대해 아는대로 설명하라

**Comment by kevin123488** [comment]
ARP 프로토콜: 같은 네트워크 대역에서 통신을 하기 위해 필요한 MAC 주소를 IP주소를 이용해서 알아오는 프로토콜
RARP: IP호스트가 자신의 물리 네트워크 주소(MAC)는 알지만 IP주소를 모르는 경우, 서버로부터 IP주소를 요청하기 위해 사용

**Comment by ohhamin** [comment]
몰라용

**Comment by dudupeng3105** [comment]
RAPP가 뭔데용

**Comment by nuriring** [comment]
RARP는 역순 주소 결정 프로토콜(Reverse Address Resolution Protocol, RARP)은 IP호스트가 자신의 물리 네트워크 주소(MAC)는 알지만 IP주소를 모르는 경우, 서버로부터 IP주소를 요청하기 위해 사용한다. (BY 구글)

**Comment by bds01088** [comment]
몰?루

**Comment by wns0394** [comment]
arp는  같은 네트워크 대역에서 통신하는데 mac주소를 ip주소를 이용해서 알아오는 프로토콜
