### ISSUE TITLE
ARP 프로토콜의 구성

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#27]

**Comment by kevin123488** [comment]
hardware type, protocol type, hardware address length, protocol address length, opcode, source hardware address, source protocol address, destination hardware address, destination protocol address 총 28바이트로 구성됨

**Comment by dudupeng3105** [comment]
hardware type(보통 이더넷, 0 0 0 1), protocol type(Ipv4 0 8 0 0), hardware address length(0 6, 맥주소길이), protocol address length(0 4, 프로토콜 길이), opcode(0 0 0 1/2, 1(request), 2(response)), source hardware address(6바이트), source protocol address(4바이트), destination hardware address(6바이트), destinationprotocol address(4바이트),

**Comment by nuriring** [comment]
ARP 프로토콜은 ARP가 요청인지, 응답인지 구분하는 OP코드, IP 주소, MAC 주소, 이더넷 헤더, 프로토콜타입으로 구성됩니다.

**Comment by bds01088** [comment]
하드웨어타입, 프로토콜타입, MAC 주소 길이, IP 길이, 명령어코드, 보내는 MAC 주소, 보내는 IP 주소, 받는 MAC주소, 받는 IP 주소

**Comment by mouseJAVA777** [comment]
![image](https://user-images.githubusercontent.com/104047116/187071698-a8345f55-a534-4637-ae30-ecbedab8551d.png)

**Comment by wns0394** [comment]
op코드,  보내는 mac주소 ip주소 받는 mac주소 ip주소
