### ISSUE TITLE
크기 1514 바이트짜리 패킷을 자주 볼 수 있는 이유는?

### ISSUE THREAD

**Issue by kevin123488** [mouseJAVA777/class_md#28]

**Comment by mouseJAVA777** [comment]
문제 좋네요

**Comment by dudupeng3105** [comment]
보통 MTU가 1500바이트이고, 거기에 이더넷 헤더(14byte)붙이면 1514 바이트이기 때문이에요

**Comment by nuriring** [comment]
MTU 1500바이트 + 이더넷헤더 14바이트

**Comment by hula-la** [comment]
보통 MTU가 1500바이트여서 
20 bytes(IP header) + 1480 bytes(data) + 14 bytes(etherner header)

**Comment by ohhamin** [comment]
MTU는 보통 1500 이더넷 추가하면 1514

**Comment by bds01088** [comment]
기본 MTU 크기 = 1500 인데 3계층까지 패킷의 크기가 MTU보다 작거나 같아야하고, 캡슐화 이후 이더넷 헤더가 붙게되면 14바이트가 더 붙기 때문

**Comment by wns0394** [comment]
데이터 1480 + IP 20 + 이더넷 14
