### ISSUE TITLE
2계층 Ethernet 프로토콜의  Ethernet Type의 역할을 간단히 설명하라

### ISSUE THREAD

**Issue by dudupeng3105** [mouseJAVA777/class_md#3]

**Comment by bds01088** [comment]
3계층의 프로토콜이 어떤것인지 알려준다

**Comment by kevin123488** [comment]
페이로드 안의 상위 프로토콜 내용을 미리 알려주는 역할(받는 쪽으로 하여금 이더넷 프로토콜을 받고 분석을 할 수 있게 하기 위함)

**Comment by CHOIJXWXN** [comment]
상위 프로토콜 미리보기

**Comment by nuriring** [comment]
Ethernet type에는 상위 계층의 프로토콜을 알려주는 바이트가 담겨져 있습니다. 예를 들어 IPv4의 경우 80 00 이 담겨져 있음

**Comment by mouseJAVA777** [comment]
어떤 프로토콜인지 알려주는 역할을 수행함. 이 부분이 없으면 어떤 프로토콜인지 알 수 없어서 읽지 못함.

**Comment by ohhamin** [comment]
다음 프로토콜이 뭔지 알려줌

**Comment by hula-la** [comment]
3계층의 패킷 타입을 명시하는 역할을 함.
