### ISSUE TITLE
UDP는 전송방식이 너무 단순해서 서비스의 신뢰성이 낮고, 누락의 가능성이 크다 그러면 도대체 UDP는 어디에 쓸 수 있을까?

### ISSUE THREAD

**Issue by dudupeng3105** [mouseJAVA777/class_md#32]

**Comment by kevin123488** [comment]
오류의 검사와 수정이 필요 없는 프로그램에서 수행

**Comment by nuriring** [comment]
TFTPD 파일전송..?

**Comment by ohhamin** [comment]
DNS서버(도메인을 물어보면 IP를 알려줌)
tftpd
RIP 프로토콜(라우팅 정보 공유)
동영상 스트리밍(TCP와 혼용함)
운영체제가 깔리지 않은 PC에 데이터를 줄 때

**Comment by bds01088** [comment]
오류의 검사와 수정이 필요없는 프로그램
중간에 데이터가 누락되어도 큰 차이를 느끼지 못하는 것?

**Comment by hula-la** [comment]
실시간성이 보장되어야 하는 동영상 스트리밍 같은 것

**Comment by dudupeng3105** [comment]
답지공개
첫번째, 음성 및 비디오를 위한 실시간 스트리밍 서비스이다. 
음성서비스를 TCP로 할 경우의 문제점은 중간에 패킷이 빠질 경우 
음성서비스가 중단된다는 점이다. 
즉, 전화를 하다가 잡음이 생기면 바로 전화가 끊어져버리는 것과 마찬가지다. 
따라서 통신 품질보다는 통신의 연속성이 더욱 중요시되는 곳에 
유용하게 사용될 수 있다. (하지만 TCP로도 UDP처럼 구현할 수 있고 
상당수의 서비스가 TCP로 서비스된다고 한다^^; 단순 특징을 설명한 것이다.)
 
두번째, 상당히 많은 패킷이 오고 가면서 
별로 중요하지 않은 몇개의 데이터 손실 정도는 눈 감아줄 수 있는 곳에 사용된다. 
예시로 starcraft의 배틀넷 서비스를 들 수 있다. 
배틀넷은 수많은 유저가 접속해서 사용하는데 서비스의 
모든 부분에 TCP를 사용하기엔 좀 느린 감이 있다. 
그리고 게임을 할 때 서로 교환되는 수많은 패킷은 중요한 데이터가 
아니기도 하고 게임의 흐름이 끊기면 안되기 때문에 UDP로 처리하는 것이 더 유리하다.
https://6kkki.tistory.com/19 [NATION OF 6KKKI:티스토리]
