### ISSUE TITLE
ICMP 프로토콜의 Type에서 0번, 8번, 3번, 11번이 의미하는 것을 서술하시오.

### ISSUE THREAD

**Issue by nuriring** [mouseJAVA777/class_md#33]

**Comment by dudupeng3105** [comment]
0번 응답, 8번 요청, 3번 도달하지 못함, 11번 타임 오버

**Comment by CHOIJXWXN** [comment]
0 : 응답
8 : 요청
3 : 목적지까지 못감
11 : 목적지까지 갔는데 응답 받지 못함 (방화벽 문제 등을 이유로)

**Comment by wns0394** [comment]
0 응답 8 요청
3 목적지로 가지 못함
11 목적지까지 갔지만 응답을 못받음

**Comment by ohhamin** [comment]
그게 맞음

**Comment by kevin123488** [comment]
0번: 응답, 8번: 요청, 3번: 목적지 도달 불가, 11번: 요청 시간 만료

**Comment by bds01088** [comment]
0 : 응답
8 : 요청
3 : 목적지 미도착
11 : TTL? 만료

**Comment by hula-la** [comment]
0 응답
8 요청
3 목적지 도달 X (경로 잘못)
11 요청 시간 만료 (상대 잘못)

**Comment by mouseJAVA777** [comment]
0 : echo reply
3 : destination unreachable
5 : redirect
8 : echo request
11 : time exceeded

**Comment by nuriring** [comment]
답지공개
0번(Echo Reply)은 응답, 3번(Destination Unreachable)은 목적지까지 가지 못했음(라우터나 경로설정을 잘못해서 목적지까지 못간 경우), 5번(Redirect)은 원격지에있는 라우팅 테이블을 icmp를 통해서 수정, 8번(Echo)은 요청, 11번(Time Exceded)은 목적지까지 갔는데 응답을 못받음(상대방이 방화벽 켜놨을 때)
