### ISSUE TITLE
라우팅 테이블이란?

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#34]

**Comment by nuriring** [comment]
라우팅 테이블은 네트워크 통신의 지도로서, 목적지 IP 주소를 알려주는 지표 역할을 한다

**Comment by wns0394** [comment]
네트워크와 통신하기 위해서 네트워크 대역의 목적지를 알려주는 지도

**Comment by hula-la** [comment]
3계층에서 최적의 경로로 통신할 때, 경로를 지도처럼 저장해 놓은 것
목적지 IP를 봤을 때 최적의 다음 IP를 알 수 있음...?

**Comment by dudupeng3105** [comment]
기억이 안남, 라우팅 테이블에 있는 네트워크대역만 통신이 갈 수 있다고 알고있음

**Comment by bds01088** [comment]
해당 기기의 라우팅 테이블에 IP주소가 있어야지 통신이 가능하며, 주로 작성되어있는 최적의 경로와 해당 경로가 없을 경우 무조건 게이트웨이 IP로 보내주는 경로를 지정한다..?

**Comment by mouseJAVA777** [comment]
목적지 주소를 목적지에 도달하기 위한 네트워크 노선으로 변환시키는 목적으로 사용되는 테이블

**Comment by kevin123488** [comment]
cmd 열고 netstat -r 쳐서 확인해보셈
