### ISSUE TITLE
UDP 프로토콜은 전송 방식은 너무 단순해서 서비스의 신뢰성이 낮고 데이터그램도착 순서가 바뀌거나 중복되거나 심지어는 통보없이 누락시키기도 한다. 그럼에도 불구하고 사용하는 이유는 무엇인가???

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#35]

**Comment by ohhamin** [comment]
전송 방식이 단순해서?

**Comment by CHOIJXWXN** [comment]
크기가 작음?

**Comment by dudupeng3105** [comment]
신뢰성이 낮은 것이 어떨 때는 도움이 될 수 있다. 예를 들어 TCP 프로토콜의 경우 누락이나 중복 발생 시 통신이 중단되지만, UDP의 경우에는 신경 쓰지 않기 때문에 계속 통신이 이어진다. 그래서 음성 서비스의 경우 중간에 어떤 데이터가 누락되어도 큰 문제가 아니고, 음성 서비스가 계속해서 진행되는 것이 중요하다. 이럴 경우 UDP를 쓴다.

**Comment by mouseJAVA777** [comment]
별 생각 없었는데 두두펭님한테 많이 배워갑니다

**Comment by bds01088** [comment]
두두펭님의 말을 따라 제가 생각하기에는 통신의 지속성이 좋은거 같습니다

**Comment by hula-la** [comment]
갓두두펭
