### ISSUE TITLE
포트 번호를 분류하는 세가지 기준은 무엇인가?

### ISSUE THREAD

**Issue by nuriring** [mouseJAVA777/class_md#36]

**Comment by mouseJAVA777** [comment]
![image](https://user-images.githubusercontent.com/104047116/188310083-21c4ddcd-f9dd-4cdf-98b3-01f3b52f838e.png)

**Comment by ohhamin** [comment]
그게 맞음

**Comment by dudupeng3105** [comment]
그게 맞는데, 80포트는 http고 443포트는 https이고, dns 53포트이다

**Comment by kevin123488** [comment]
유명도를 기준으로? 분류

**Comment by hula-la** [comment]
그게 맞나봐

**Comment by bds01088** [comment]
웰노운, 레지스터드, 다이나믹 순으로 유명한 순으로 짱 먹음
