### ISSUE TITLE
프로세스란?

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#37]

**Comment by CHOIJXWXN** [comment]
메모리에 올라간 프로그램

**Comment by dudupeng3105** [comment]
메모리에서 동작 중인 프로그램
성단장님의 프로세스는 언제...

**Comment by wns0394** [comment]
메모리에서 동작 중인 프로그램

**Comment by nuriring** [comment]
그게 맞아

**Comment by mouseJAVA777** [comment]
디스크에 저장된 프로그램 중 메모리에서 실행중인 프로그램

**Comment by kevin123488** [comment]
위에 말이 다 맞음

**Comment by hula-la** [comment]
프로그램이 파일 시스템에 저장되어 있는 정적인 상태인 것이면,
프로세스는 프로그램이 메모리에 올라간 동적인 상태, 프로그램의 인스턴스이기도 함.

**Comment by bds01088** [comment]
프로세스는 실행중인 프로그램이다
