### ISSUE TITLE
IPv4 프로토콜 구조에서 하나의 데이터를 여러개의 데이터로 쪼개었을 때  id가 같아야하는 이유는 무엇인가?

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#39]

**Comment by CHOIJXWXN** [comment]
조각화된 데이터를 다시 합칠 때 원래 같은 데이터였는지 확인하기 위함

**Comment by dudupeng3105** [comment]
조각화된 데이터는 순서를 보장할 수 없다. 그래서 id를 보고 조각들을 합쳐 원래의 데이터로 만들 수 있다.

**Comment by mouseJAVA777** [comment]
보낼 때 순서대로 보내더라도 받을 때는 순서가 보장되어있지 않기 때문에 ID 정보를 통해 순서를 맞춘다.

**Comment by ohhamin** [comment]
나중에 합치려고

**Comment by nuriring** [comment]
쪼개진 데이터를 하나로 합칠때 , 같은 ID 번호로 본래 하나였던 데이터임을 증명할 수 있음

**Comment by kevin123488** [comment]
합칠 때 id를 기준으로 합칠 애들을 판별

**Comment by hula-la** [comment]
같은 데이턴지 확인하기 위해서

**Comment by bds01088** [comment]
조각된 데이터들을 다시 합쳐야하기 때문에
