### ISSUE TITLE
하나의 LAN 대역을 만들 때 주로 Star형 연결을 사용한다고 한다. 그 이유는?

### ISSUE THREAD

**Issue by kevin123488** [mouseJAVA777/class_md#4]

**Comment by dudupeng3105** [comment]
비용적인 문제가 크다고 본다. mesh형의 경우가 더 안정적이지만, 하지만 모든 노드 간의 연결이 필요하므로 n개의 노드일 경우 n(n-1)/2 개의 노드 간의 케이블이 필요하다 하지만 Star의 경우 N개의 경우 가운데 중앙 장비 기준으로 N개의 케이블이 필요하므로 경제적이다.

**Comment by ohhamin** [comment]
싸서. 전선을 더 많이 쓰게되면 전선 가격도 더 나가게되고 길이가 길어지면 데이터를 전송하는데 더 힘들게 된다. 그래서 LAN 대역을 만들때에는 mesh보다 안전하진 않지만 star 형 연결을 사용하여 더 적은 비용으로 통신할 수 있게 한다.

**Comment by nuriring** [comment]
star형 연결을 사용하면 중앙에서 다른 서버로 퍼지 듯이 구성할 수 있기 때문에 초기 구축이 간단할 것이다.

**Comment by mouseJAVA777** [comment]
중앙 장비가 고장나면 전체의 연결도 끊기지만, 반대로 중앙 장비만 멀쩡하면 연결된 장비들도 통신이 가능할 가능성이 높음. 적은 비용으로 비교적 높은 효율 추구

**Comment by CHOIJXWXN** [comment]
근거리에 있기 때문에 통신하는데 있어서 큰 어려움이 없다. 비록 중앙에서 연결 장애가 생겼을 때 시스템 전체가 다운되지만 근거리이므로 충분히 통제 가능한 범위라고 볼 수 있어 빠르게 복구할 수 있으므로 굳이 번거롭고 비용이 높은 메시형을 사용할 필요가 없다.

**Comment by bds01088** [comment]
근거리는 정비하기 쉽고 저렴하기 때문에

**Comment by hula-la** [comment]
우선 근거리는 거리가 짧기 때문에 오류가 발생할 확률이 작음. 따라서 star형이 제일 효율적임.
mesh형은 하나가 잘못돼도 다른게 연결되어 있어 문제없다는 장점이 있는데, 근거리같은 경우는 하나가 잘못돼도 수리가 비교적 간단하기도 하고 오류 발생 확률이 작기 때문에 비용/유지보수 전체적으로 봤을 때 star형이 효율적임
