### ISSUE TITLE
4계층에서 하는 일은?

### ISSUE THREAD

**Issue by bds01088** [mouseJAVA777/class_md#40]

**Comment by dudupeng3105** [comment]
전송계층, 송신자의 프로세스와 수신자의 프로세스 연결하는 통신 서비스 제공

**Comment by mouseJAVA777** [comment]
4계층 : 전송 계층이며, 송신자의 프로세스와 수신자의 프로세스를 연결하는 통신 서비스를 제공한다

- 프로세스란? : 디스크에 저장되어있는 프로그램 중 메모리에서 동작중인 프로그램

: 즉, 내 컴퓨터에서 동작중인 프로그램과, 상대방의 컴퓨터에서 동작중인 프로그램을 연결하는 통신 서비스

**Comment by ohhamin** [comment]
송신자의 프로세스와 수신자의 프로세스를 연결
예를들어 카톡을 보내면 딴사람 카톡에 보낸게 뜸

**Comment by nuriring** [comment]
그게 맞아

**Comment by wns0394** [comment]
4계층에서 하는 일은 전송  계층 송신자의 프로세스와 수신자의 프로세스를 연결하는 통신 서비스

**Comment by kevin123488** [comment]
송신자의 프로세스와 수신자의 프로세스를 연결하는 통신 서비스 제공

**Comment by hula-la** [comment]
위에 말이 다 맞아요
