### ISSUE TITLE
포트포워딩은 언제 사용하는지 설명하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#41]

**Comment by ohhamin** [comment]
통신하고자 하는 대상이 사설 IP를 쓰기 때문에 내가 알 수 없을 때

**Comment by bds01088** [comment]
데이터를 전달할 대상의 사설 IP는 모르고 공인 IP만 알 때,
공유기가 설정해놓은 포트포워딩을 통해 특정 포트로 보내면 정해진 사설 IP로 전달되어 이용 가능하다

**Comment by mouseJAVA777** [comment]
공인 아이피로 들어오는 연결을 사설 ip로 연결해주는 설정

**Comment by nuriring** [comment]
특정 ip와 특정포트번호로 들어온 신호를 다른 특정 ip와 특정포트번호로 보낼 때 사용한다

**Comment by dudupeng3105** [comment]
특정 ip와 특정포트번호로 들어온 신호를 다른 ip와 다른포트번호로 보낼 때 사용

**Comment by hula-la** [comment]
외부의 기기의 입장에서 봤을 때 내부의 기기는 숨겨져 있음.
공인 IP의 특정 포트로 신호를 보내면 사설 IP(내부 기기)의 특정 포트로 전달 해줌.

**Comment by wns0394** [comment]
특정 IP 주소와 포트 번호의 통신 요청을 특정 다른 IP와 포트 번호로 넘겨줄 때 사용
