### ISSUE TITLE
UDP프로토콜과 TCP 프로토콜의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#42]

**Comment by CHOIJXWXN** [comment]
TCP가 더 안정적이고 데이터 로스가 없어서 UDP보다는 안전하지만 느린 단점을 가지고 있다

**Comment by ohhamin** [comment]
TCP는 확인 과정이 많아 데이터를 더 안정적으로 보내지만 좀 느리다 근데 느린거 알아채면 초능력자임

**Comment by dudupeng3105** [comment]
TCP는 TCP flag, ack, seq. number 를 이용한 확인 절차가 있어서 안정적, 순차적, 에러 없이 통신을 교환할 수 있다. 그러나 확인 절차 때문에 속도가 느림

**Comment by bds01088** [comment]
UDP는 단순히 데이터를 전달만 한다면, TCP는 데이터가 잘 도착했는지 확인하고 그 응답도 주고받으면서 데이터의 유지력을 강화하여 통신할 수 있다. 절차가 존재하여 UDP보다 느리지만 그렇게 많이 차이나지는 않는다는 것이 강의에서의 설명

**Comment by mouseJAVA777** [comment]
UDP : 비연결형 프로토콜 (신뢰성보다 연속성이 중요한 서비스) -> 스트리밍
TCP : 연속성보다 신뢰성 있는 전송이 중요할 때 사용하는 프로토콜

**Comment by hula-la** [comment]
UDP: 신뢰성없이 빠르게 데이터를 전달, 비연결형
TCP: 느리지만 신뢰성있게 데이터 전달, 연결형
