### ISSUE TITLE
3Way Handshake란?

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#43]

**Comment by CHOIJXWXN** [comment]
1. 클라이언트가 서버에게 요청
2. 서버가 클라이언트의 요청을 수락
3. 클라이언트가 서버의 수락하는 패킷을 수신
-> 데이터 통신을 위해 연결을 땅땅땅하는 단계

**Comment by wns0394** [comment]
클라이언트가 서버에게 요청
서버가 요청을 받아들이고 다시 클라이언트에게 요청
클라이언트가 수락

**Comment by bds01088** [comment]
TCP 프로토콜을 통하여 데이터를 주고 받기 위해서는 상대방과 연결이 되어야하는데,
연결할 당시 서로가 인식하도록 하는 방법이다.
먼저 클라이언트가 서버에게 연결 요청을 보내고, 서버가 받고 연결할게 하고 다시 응답하면, 클라이언트가 응답 잘받았다고 확인 안부를 전하는 것을 3way handshake라고 한다

**Comment by mouseJAVA777** [comment]
tcp를 이용한 데이터 통신을 할 때 프로세스와 프로세스를 연겨라기 위해 가장 먼저 수행되는 과정으로 

1. 클라이언트가 서버에게 요청 패킷을 보내고
2. 서버가 클라이언트의 요청을 받아들이는 패킷을 보내고
3. 클라이언트가 이를 최종적으로 수락하는 패킷을 보낸다

**Comment by nuriring** [comment]
클라이언트가 서버에게 요청
서버가 클라이언트의 요청을 받아들임
클라이언트가 이를 수락

**Comment by dudupeng3105** [comment]
클라이언트(Syn_sent)가 서버(Syn_Received)에게 요청
서버(Syn_Received)가 클라이언트(Syn_sent) 요청 수락
클라이언트가 이를 수락(Established)

**Comment by hula-la** [comment]
1. 클라이언트-> 서버: Syn (요청)
2. 서버 -> 클라이언트: Syn+ACK (요청 수락)
3. 클 -> 서: ACK (수락)
