### ISSUE TITLE
GET 방식과 POST 방식의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#44]

**Comment by ohhamin** [comment]
GET방식은 데이터를 주소창에 포함시켜 넘기고 POST는 BODY에 담아 보내서 중요한 데이터를 숨길 수 있다. 요즘은 이거도 다 빼가서 https 씀

**Comment by CHOIJXWXN** [comment]
GET은 쿼리를 통해서 데이터를 보내고 POST는 바디에 담아서 보낼 수 있음
GET은 POST에 비해 보안에 취약하고 데이터 전송에 제한이 있음

**Comment by dudupeng3105** [comment]
GET방식은 쿼리를 통해 데이터를 넘길 수 있으나, 주소에 데이터가 노출되는 단점이 있다. 그래서 아이디 비밀번호 같은 데이터는 GET방식으로 하기에는 보안 문제가 있음. POST는 바디에 숨겨서 보낼 수 있으나 이것마저 캡쳐할 수 있으므로 정말 보안이 필요한 데이터는 HTTPS를 사용한다.

**Comment by bds01088** [comment]
GET은 URI에 데이터가 눈에 보이고, POST는 http 프로토콜 body 부분에 데이터를 담아서 보내므로 보이지 않는다.

**Comment by mouseJAVA777** [comment]
dodopeng에 동의합니다. 
GET : 쿼리를 통해 데이터를 넘길 수 있다. 주소에 데이터가 노출된다. 
POST : body에 데이터를 담아서 보낸다. 
정말 보안이 필요한 데이터는 https를 활용한다. 

굿

**Comment by nuriring** [comment]
get 방식은 쿼리문에 정보가 담겨있고, post 방식은 body에 정보가 담겨 있다.

**Comment by hula-la** [comment]
GET: URI에 데이터를 넣어서 보내서, 예민한 정보를 전달할 땐 지양, 데이터 크기 제한있음.
POST: body에 정보를 담아서 비교적으론 보안적, 데이터 크기 제한 없음.
