### ISSUE TITLE
SEQ과 ACK번호가 탈취되면 안 되는 이유를 설명하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#45]

**Comment by ohhamin** [comment]
내가 아닌 다른 사용자에게 요청 된 데이터들이 갈 수 있다. 해킹조심

**Comment by wns0394** [comment]
보안상의 이유로 악용한다면 통신에 접근이 가능함

**Comment by bds01088** [comment]
SEQ와 ACK를 탈취당하면, 이를 이용하여 세션 하이재킹이 가능해진다. 연결은 클라이언트A 가 했는데 데이터를 주고 받는 것은 하이재킹한 클라이언트 B가 해당 SEQ와 ACK를 통하여 서버와 연결될 수 있기 때문.

**Comment by dudupeng3105** [comment]
다른 사람이 세션을 가로채서 통신을 할 수 있다.

**Comment by mouseJAVA777** [comment]
TCP의 식별정보를 공격자가 위조하여 세션을 탈취당할 수 있음

**Comment by hula-la** [comment]
클라이언트 A가 서버랑 3 way handshake를 통해 서로 연결을 수락했지만
클라이언트 B가 SEQ와 ACK 번호를 안다면, A인척 서버랑 통신할 수 있음.
