### ISSUE TITLE
uri의 구조를 적으세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#46]

**Comment by ohhamin** [comment]
scheme :// ip주소:포트번호(도메인으로 바꿀 수 있음) / 경로 ?쿼리

**Comment by dudupeng3105** [comment]
scheme :// host[:port][/path][?query]
port는 웹 브라우저가 알아서 해줘서 생략이 가능하긴 함

**Comment by bds01088** [comment]
# schema(개요)와 scheme(계획)은 다른 단어다
프로토콜 :// ip주소:포트번호or도메인 /경로 /?쿼리

**Comment by wns0394** [comment]
scheme :// host[:port][/path][?query]

**Comment by mouseJAVA777** [comment]
scheme
host
port
path
query

**Comment by nuriring** [comment]
scheme :// host[:port][/path][?query]
