### ISSUE TITLE
NAT란?

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#47]

**Comment by wns0394** [comment]
특정 IP 주소의 특정 포트번호로 가는 패킷을 다른 IP 주소의 다른 포트번호로 바꿔주는 것

**Comment by bds01088** [comment]
network address translation
주로 사설IP와 공인IP를 구축하는데 자주 쓰이며, IP주소를 변경해주는 장치?

**Comment by mouseJAVA777** [comment]
네트워크 주소 변환 
ipv6에서는 사실상 필요없지만, 아직까지 IPv4가 대다수 사용되기 때문에 사용되고있음

**Comment by dudupeng3105** [comment]
특정 IP 주소의 특정 포트번호로 가는 패킷을 다른 IP 주소의 다른 포트번호로 바꿔주는 것

**Comment by nuriring** [comment]
NAT(Network Address Translation)
- IP 패킷의 TCP/UDB 포트 숫자와 소스 및 목적지의 IP 주소 등을 재기록하면서 라우터를 통해 네트워크 트래픽을 주고 받는 기술
