### ISSUE TITLE
HTTP 1.0의 단점과 HTTP 1.1이 나온 이유

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#49]

**Comment by wns0394** [comment]
연결수립, 요청, 응답을 계속 반복해야해서 HTTP 1.1이 나옴

**Comment by dudupeng3105** [comment]
만약에 이미지 10개에 대한 데이터를 가져오려면 1.0의 경우에는 핸드쉐이크-데이터요청-응답의 과정을 10번 해야함
1.1의 경우 한 번의 핸드쉐이크 후 연결 유지 상태로 데이터 요청 - 응답의 과정만 10번 하면 됨
핸드쉐이크를 여러번 할 필요 없다.

**Comment by bds01088** [comment]
데이터를 주고 받을 때 마다 handshake를 매번 해야하기 때문에 너무 느리고 구림
한번 연결했을때 데이터를 계속 주고 받을 수 있도록 변경함

**Comment by nuriring** [comment]
데이터를 주고 받을 때마다 재연결 하는 것이 아니라, 계속 연결 된 상태에서 데이터를 주고 받을 수 있음

**Comment by hula-la** [comment]
데이터를 주고받을 때마다 핸드쉨 과정이 필요했는데,
HTTP 1.1은 한번만 핸드쉨하면 끝낼 때(fck?)까지 계속 데이터 주고 받을 수 있음.
