### ISSUE TITLE
Mesh형 연결의 경우 어느 장비 하나가 고장난다 해도 전체적인 통신에는 문제가 없다고 한다. 그 이유는?

### ISSUE THREAD

**Issue by kevin123488** [mouseJAVA777/class_md#5]

**Comment by dudupeng3105** [comment]
왜냐하면 다른 노드를 거쳐서 연결될 수 있기 때문이다. 예를 들어 a-b, b-c, a-c 로 연결되어 있다고 하자 만약 a-b가 끊어진다고 해도 a는 c를 거쳐 b와 연결될 수 있다.

**Comment by bds01088** [comment]
하나의 연결선이 망가진다해도 연결된 다른 노드들을 통해 접속할 수 있기 때문에

**Comment by ohhamin** [comment]
연결된 노드가 그물처럼 되어있기 때문에 하나의 노드가 망가져도 다른 노드를 통해 통신할 수 있음

**Comment by nuriring** [comment]
중앙집중식이 아닌 그물형이기 때문에 하나의 서버가 고장이 나도 인근 서버에 연결된 망을 가져다가 사용할 수 있습니다.

**Comment by mouseJAVA777** [comment]
한국에서 일본으로 가는 노드가 손상이 되었더라도, 다른 가능한 경로로 우회해서 접근할 수 있음.

**Comment by CHOIJXWXN** [comment]
고장난 장비를 통한 연결에만 의존하지 않기 때문에 다른 노드를 통해서 원하는 노드와 연결이 가능하다.

**Comment by hula-la** [comment]
전체 노드가 서로 연결이 되어 있기 때문에 하나가 고장나도 다른 정상 노드와 연결되어 있으면 됨.
