### ISSUE TITLE
TCP 연결을 통한 데이터 전달 과정 내용을 참고하여 작성하세요

### ISSUE THREAD

**Issue by bds01088** [mouseJAVA777/class_md#50]
연결 수립 과정 마무리 단계 당시 s : 702, a : 1102  요청 payload 길이: 40 , 응답 payload 길이 : 80

**Comment by dudupeng3105** [comment]
1. A가 요청 s : 702 a : 1102 payload: 40
2. B가 응답 s : 1102 a : 742 payload: 80
3. A가 당시 요청하면 s : 742 a : 1182
?..

**Comment by ohhamin** [comment]
s702 a 1102
s1102 a742
s742 a1182

**Comment by wns0394** [comment]
s 702       a 1102
s 1102     a 702 + 40
s 742       a 1102 + 80

**Comment by mouseJAVA777** [comment]
몰루ㅜ
