### ISSUE TITLE
HTTP/1.0과 HTTP/1.1의 차이점은?

### ISSUE THREAD

**Issue by bds01088** [mouseJAVA777/class_md#52]

**Comment by dudupeng3105** [comment]
[복붙]만약에 이미지 10개에 대한 데이터를 가져오려면 1.0의 경우에는 핸드쉐이크-데이터요청-응답의 과정을 10번 해야함
1.1의 경우 한 번의 핸드쉐이크 후 연결 유지 상태로 데이터 요청 - 응답의 과정만 10번 하면 됨
핸드쉐이크를 여러번 할 필요 없다.

**Comment by ohhamin** [comment]
1.0은 연결 동작 해제 해서 통신의 부하가 많음
1.1은 한번 연결하면 데이터 교환을 계속 함

**Comment by wns0394** [comment]
HTTP 1.0은 연결수립 요청 응답을 반복
HTTP 1.1은 한번 연결해두면 이제 요청 응답만 한다
