### ISSUE TITLE
포트포워딩의 역할은?

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#53]
.

**Comment by ohhamin** [comment]
외부에서 내 내부 사설IP를 모를 때 공인IP에서 내가 설정한 특정 포트로 이동할 수 있게 하여 접속할 수 있게 한다.

**Comment by bds01088** [comment]
외부에서 사설 ip로 접속할 때 해당 사설 ip에서 쓰는 포트를 기준으로 특정 ip를 연결시켜주는 것?
