### ISSUE TITLE
3 way handshake에 대해 설명해주세요 

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#54]
.

**Comment by ohhamin** [comment]
1. 클라이언트가 서버에 요청을 보냄
2. 서버가 요청을 받음
3. 클라이언트가 수락함

**Comment by bds01088** [comment]
클라이언트가 연결 요청을 보냄
서버가 요청을 받고 응답을 보냄
클라이언트가 응답을 받고 establish로 변경되고 잘 받았다고 답장을 전함
서버가 답장을 받고 establish로 변경됌
