### ISSUE TITLE
TCP 3 way handshake 과정을 설명하시오.

### ISSUE THREAD

**Issue by hula-la** [mouseJAVA777/class_md#56]

**Comment by ohhamin** [comment]
1. 클라이언트가 서버에 요청을 보냄
2. 서버가 요청을 받음
3. 클라이언트가 수락함

**Comment by bds01088** [comment]
클라이언트가 서버에 연결요청 보냄
서버가 요청을 받고 응답을 보냄
클라이언트가 응답을 받고 확인했다고 답장을 보냄
