### ISSUE TITLE
POST와 GET의 차이점을 설명하시오.

### ISSUE THREAD

**Issue by hula-la** [mouseJAVA777/class_md#57]

**Comment by ohhamin** [comment]
get 방식은 데이터를 주소창에 넣어 보내고 post는 바디에 넣어 보내기 때문에 중요한 데이터를 숨길 수 있다
해커가 다 털어가서 https 써야함

**Comment by bds01088** [comment]
쿼리에 쓰이는 데이터가 uri에 존재하냐 아니냐의 차이

**Comment by wns0394** [comment]
get은 주소에 데이터를 담아서 보냄
post는 body에 넣어서 보냄
