### ISSUE TITLE
Mode bit가 하는 역할은? 

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#58]
Mode bit가 하는 역할은?
0일때 1일때로 나눠서 설명하시오

**Comment by dudupeng3105** [comment]
역할 - 2가지 운영체제의 operation 모드 구분
0 : 모니터모드(커널모드), 특권명령 가능
1 : 사용자모드

**Comment by ohhamin** [comment]
0 : OS 일때 딴데 다 접근 가능
1 : 프로그램일때 접근 제한 기능

**Comment by kevin123488** [comment]
0: 모니터 모드, os코드 실행
1: 사용자 모드,  사용자 프로그램 실행

**Comment by bds01088** [comment]
운영체제가 실행되는 지, 사용자 프로그램이 실행되는 지를 구분하기 위한 비트
0 : 커널 모드
1 : 사용자 모드

**Comment by CHOIJXWXN** [comment]
현재 CPU를 점유하는 주체를 구분
0일 때는 운영체제가 접근한 것으로 커널모드, 1일 때는 사용자 프로그램이 접근한 것으로 사용자모드
사용자 프로그램의 잘못된 수행으로 피해가 생기는 것을 방지하기 위함

**Comment by hula-la** [comment]
0: 운영체제 모드 (커널 모드)
1: 사용자 모드
사용자 모드일 때는 특정 명령들에 대해서는 제한됨.

**Comment by nuriring** [comment]
0 : 커널 모드
1 : 사용자 모드
