### ISSUE TITLE
SWAP memory 는 어떤 역할을 수행하는가 

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#59]

**Comment by dudupeng3105** [comment]
여러 프로그램들을 모두 메모리에 올리면 자원이 부족할 수 있어 HDD에 메모리 연장공간을 두어서 이를 해결할 수 있다. 잠시 안 쓰는 거 swap memory에 두거나 하는 식으로 사용함

**Comment by bds01088** [comment]
일시저장..? cache같은 느낌..? 몰?루..

**Comment by CHOIJXWXN** [comment]
당장 사용하지는 않지만 보관이 필요한 것들 저장, 휘발성이라 종료되면 없어짐

**Comment by hula-la** [comment]
메모리가 꽉 찼을 때 임시로 저장해두는 곳. 휘발성.

**Comment by nuriring** [comment]
휘발성 데이터를 임시로 저장해두는 역할

**Comment by kevin123488** [comment]
디스크 공간을 메모리처럼 사용하는 것. 데이터 임시 저장 목적
