### ISSUE TITLE
LAN과 WAN에 대해 설명하고, 차이점을 설명하시오

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#6]

**Comment by ohhamin** [comment]
LAN : 근거리통신망 WAN : 여러 LAN을 이어놓은 통신망

**Comment by kevin123488** [comment]
LAN: 가까운 지역을 묶은 네트워크
WAN: 멀리 있는 지역을 묶어놓은 네트워크(LAN과 LAN을 묶음)

**Comment by bds01088** [comment]
local area network
wide area network
랜끼리 연결시킨것이 웬

**Comment by nuriring** [comment]
LAN 은 근거리 통신망으로서 집에서 흔히 쓰는 공유기같은 것이 있고 WAN은 원거리 통신망으로서 LAN과 LAN들을 원거리에서도 이어주는 역할을 합니다.

**Comment by dudupeng3105** [comment]
LAN : 근거리 통신망
WAN : 원거리 통신망 ( LAN 끼리 원거리에서 연결해줌)

**Comment by CHOIJXWXN** [comment]
LAN은 근거리 통신망, WAN은 원거리 통신망으로 여러 LAN을 하나로 묶은 것이다.

**Comment by hula-la** [comment]
LAN은 근거리, WAN은 원거리 네트워크이며
네트워크의 지리적 범위에 따라 나눈 개념
