### ISSUE TITLE
kernel thread와 user thread에 대해 차이점을 중심으로 설명하시오

### ISSUE THREAD

**Issue by kevin123488** [mouseJAVA777/class_md#60]

**Comment by dudupeng3105** [comment]
커널 스레드는 cpu가 스레드가 있다는 것을 알 수 있음, 유저 스레드는 cpu가 모름 그래서 기능이 비교적 제한적임

**Comment by mouseJAVA777** [comment]
커널 스레드 : 운영체제가 지원하는 스레드 
유저 스레드 : 사용자 레벨의 라이브러리를 통해 구현

**Comment by hula-la** [comment]
커널 스레드
- 커널스레드는 OS에서 구현 됨.
- 커널이 각 스레드 개별적으로 관리할 수 있음
- 동작중인 스레드가 System Call(커널 호출)해도 해당 프로세스 내 다른 스레드가 계속 실행될 수 있음.
- 사용자레벨 스레드에 비교해서, 생성 및 관리가 느림.

사용자 스레드
- 스레드 기능을 제공하는 라이브러리 활용하는 방식
- 사용자 영역에서 스레드 연산 수행
- 커널 입장에서는 하나의 프로세스로 인식
- 하나의 스레드가 중단되면 같은 프로세스 내의 모든 스레드 중단됨.
- 동일한 메모리 영역에서 스레드가 생성, 관리되므로 속도가 빠름.
by [구글링](https://colinch4.github.io/2020-02-02/%EC%BB%A4%EB%84%90%EB%A0%88%EB%B2%A8%EC%8A%A4%EB%A0%88%EB%93%9C-vs-%EC%9C%A0%EC%A0%80%EB%A0%88%EB%B2%A8%EC%8A%A4%EB%A0%88%EB%93%9C/)
