### ISSUE TITLE
프로세스와 쓰레드의 차이점을 설명하시오

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#64]

**Comment by dudupeng3105** [comment]
프로세스는 CPU의 실행 단위임, 그래서 이거를 Process Control block으로 관리함 
스레드는 같은 프로세스 안에서 최대한 자원을 공유하면서 실행 단위가 여러 개 인 것처럼 작동함
스레드는 PCB의 pc, reg. stack만 각 각 다르고 다른 부분은 프로세스의 것을 공유함
이렇게 하면 장점이 프로세스를 변경하는 거보다, 스레드를 변경하는 것이 오버헤드가 적어 효율적임

**Comment by mouseJAVA777** [comment]
프로세스 : 실행될 때 운영체제로부터 자원을 할당받는데, 이 작업의 단위 
스레드 : 프로세스가 할당받은 자원을 이용하는 실행의 단위

**Comment by nuriring** [comment]
프로세스 : 운영체제로부터 자원을 할당 받음
스레드: 한 프로세스 내에서 동작되는 실행의 단위

**Comment by CHOIJXWXN** [comment]
프로세스는 메모리에 올라간 프로그램이고 운영체제한테 자원 할당 받음
스레드는 프로세스 실행 단위라서 프로세스한테 자원을 할당 받음

**Comment by hula-la** [comment]
프로세스: 운영체제로부터 자원을 할당 받을 수 있는 작업 단위
스레드: 프로세스의 실행단위
스레드는 프로세스의 자원(Code, Data,Heap)을 공유하고 Stack, Cpu관련 정보(PC, register)는 따로 가짐.

**Comment by kevin123488** [comment]
프로세스: 운영체제한테 자원 할당받음,
스레드: 프로세스의 실행 단위

**Comment by bds01088** [comment]
프로세스 : 운영체제 할당 단위
스레드 : 프로세스 실행 단위
