### ISSUE TITLE
timer가 존재하는 이유는?

### ISSUE THREAD

**Issue by bds01088** [mouseJAVA777/class_md#65]

**Comment by kevin123488** [comment]
CPU를 특정 프로그램이 독점하지 못하게 하기 위해

**Comment by ohhamin** [comment]
한 프로그램이 CPU 독점 방지

**Comment by mouseJAVA777** [comment]
프로그램이 CPU를 지속적으로 사용하는 것을 막기 위해

**Comment by dudupeng3105** [comment]
프로그램이 CPU를 독점하지 못하게
ㅋ

**Comment by CHOIJXWXN** [comment]
무한루프 돌면 골때려서

**Comment by hula-la** [comment]
무한 루프에 빠지게 되면 시스템이 CPU를 독점하게 되는데, 이를 방지
CPU 점유율을 공평하게 배분해주기 위함

**Comment by wns0394** [comment]
프로그램이 cpu를 독점하지 못하도록 예를들면 무한루프 드가면 답도없다

**Comment by nuriring** [comment]
CPU 독점방지
