### ISSUE TITLE
사용자 프로그램에서 IO 디바이스 접근하기 위해 실행되는 인터럽트의 명칭과 진행 순서를 적으시오

### ISSUE THREAD

**Issue by bds01088** [mouseJAVA777/class_md#66]

**Comment by hula-la** [comment]
시스템 콜 (소프트웨어 인터럽트)
- 사용자 프로그램이 IO 디바이스에 접근하려고 함.
- 시스템 콜
- 커널 모드로 전환 됨.
- IO 디바이스 컨트롤러에 명령함.
- 사용자모드로 전환 됨. (동기식일 경우는 다른 프로세스, 비동기일 경우는 동일한 프로세스에게 CPU 넘길듯?)

**Comment by CHOIJXWXN** [comment]
사용자 프로그램이 CPU에 인터럽트를 걸어서 OS를 호출 (시스템콜)
올바른지 확인하고 IO 수행 (CPU는 이미 다른 거 하고 있음)
IO 할 거 끝나면 인터럽트(하드웨어 인터럽트) 걸어서 본래 사용자 프로그램이 시스템콜 이후에 하려했던 명령으로 옮김

**Comment by dudupeng3105** [comment]
사용자 프로그램이 IO 디바이스 접근해야함 -> 시스템 콜 -> 커널 모드 -> 올바른 요청인지 확인 -> 수행 -> I/O 완료 시 CPU 제어권을 다시 사용자 프로그램에 넘김
몰?루
