### ISSUE TITLE
동기식 입출력과 비동기식 입출력의 차이를 설명하시오

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#68]

**Comment by kevin123488** [comment]
동기식 입출력: 입출력 요청 후 작업이 완료된 후에 제어가 사용자 프로그램으로 넘어감,
비동기식 입출력: 입출력 요청이 시작된 후 입출력 작업이 끝나기를 기다리지 않고, 제어가 사용자 프로그램으로 즉시 넘어감

**Comment by ohhamin** [comment]
동기식 : 작업 다 해야댐
비동기식 : 작업 다 안기다리고 다음거 함

**Comment by dudupeng3105** [comment]
동기식 입출력: 입출력 요청을 보내고 입출력 프로세스가 끝나야 해당 프로그램이 다시 CPU를 사용할 수 있음
하지만 구현방식에 따라 입출력 프로세스 요청을 보내고 해당 프로그램이 아닌 다른 프로그램이 CPU를 쓰는 방식도 있음
이 경우에도 똑같이 요청을 보낸 프로그램은 CPU를 사용할 수 없음
비동기식 입출력: 입출력 요청을 보내고 해당 프로그램은 CPU 제어권을 다시 가져와서 입출력 요청의 결과가 필요 없는 명령어를 수행해 효율적으로 자원 사용함

**Comment by nuriring** [comment]
두두펭과 동일하게 생각합니다

**Comment by CHOIJXWXN** [comment]
동기식은 입출력 작업이 다 끝나야 사용자 프로그램으로 제어가 넘어가지만 비동기는 그런 거 없고 작업 중에도 바로 사용자 프로그램으로 제어가 넘어감
넘어가는 프로그램이 입출력 작업을 요청한 프로그램과 다른 프로그램이면 동기식임

**Comment by hula-la** [comment]
누리와 동일하게 생각합니다.

**Comment by bds01088** [comment]
동기식 : 입출력 요청을 보내고, 응답이 올때까지 기다림
비동기식 : 입출력 요청을 보내고, 그 이외 작업을 실행함?
