### ISSUE TITLE
프로세스 상태 주요 세 가지와, 중기 스케줄러로 인해 추가되는 한 가지 상태가 각각 무엇인지 말하고 설명하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#69]

**Comment by ohhamin** [comment]
러닝 : 진행중
레디 : 대기중
블락 : I/O 같은거 기다림
서스펜디드 : 메모리에 너무 많은 프로세스가 있거나, 외부 입력으로 인해 정지

**Comment by dudupeng3105** [comment]
Running, blocked, Ready + Suspended
중기 스케줄러가 공간 마련을 위해 프로세스를 통으로 swap memory로 보내버림

**Comment by wns0394** [comment]
running : instruction 하는 중
ready :  모든 조건 만족하고 기다리는중, cpu 주어지면 수행 가능
blocked : cpu 주어져도 수행 불가능한 상태
suspended 정지

**Comment by hula-la** [comment]
- running: instruction 진행 중
- ready: 모든 조건이 만족되어, cpu만 기다리고 있는 상태
- blocked: IO 명령 수행 완료를 기다리는 중이거나 cpu가 주어줘도 명령을 수행 못하는 상태
---
- suspended: 중기 스케줄러에 의해 메모리에서 out 되거나 사용자가 멈췄을 때

**Comment by kevin123488** [comment]
Running: cpu를 잡고 instruction을 수행중인 상태,
Ready: cpu를 기다리는 상태,
Blocked: cpu를 줘도 instruction 수행 불가인 상태,
+
Suspended: 외부적 이유로 프로세스의 수행이 정지된 상태

**Comment by bds01088** [comment]
러닝 : cpu 사용중
레디 : cpu 기다리는중
블록 : cpu 사용 못하는 상태
서스팬드 : 수행이 중지된 상태
