### ISSUE TITLE
2계층에서 사용하는 주소의 이름을 말하고 그 구성과 확인 방법을 서술하시오

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#7]

**Comment by ohhamin** [comment]
처음 6자리는 수신 MAC주소, 그 다음 6자리는 송신 MAC주소

**Comment by kevin123488** [comment]
MAC주소, 식별ID와 고유번호로 구성됨, CMD에 config 하면 나옴

**Comment by nuriring** [comment]
mac 주소, mac주소는 cmd창에서 ipconfig/all 이라는 명령어를 치고 물리적 주소 뒤에 16바이트 12개 짜리 주소를 볼수 있습니다

**Comment by bds01088** [comment]
MAC 주소
cmd창에 ipconfig /all
해당 주소는 제조기업 + 기기의 고유넘버로 구성되어있다.

**Comment by dudupeng3105** [comment]
MAC 주소
앞의 3바이트 제조회사 코드, 뒤 3바이트 제품 고유넘버
cmd ipconfig/all

**Comment by hula-la** [comment]
Mac 주소
제조기업 코드 + 고유넘버
ipconfig /all 에서 물리적 주소
