### ISSUE TITLE
운영체제를 처리 방식으로 나눈다면?

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#70]

**Comment by kevin123488** [comment]
일괄 처리: 작업 요청을 일정량 모아 한번에 처리,
시분할: 여러 작업 수행시 컴퓨터 처리 능력을 일정 시간 단위로 분할하여 사용,
실시간: 정해진 시간 안에 종료가 보장되어야 하는 일이 있을 경우 이용

**Comment by dudupeng3105** [comment]
batch, time sharing, real-time
보통은 time sharing을 많이 쓴다.

**Comment by nuriring** [comment]
일괄 처리: 일정량 모아서 한번에 처리
시분할: 시간단위뢰 나눠서 사용, 주로 사용되는 방식
실시간: 반도체 공정과 같이 시간안에 처리되어야하는 방식에 사용

**Comment by mouseJAVA777** [comment]
일괄처리 : 일정량 모아서 한번에 처리
시분할 : 시간단위로 나눠서 처리 
실시간 : 시간안에 해결되는 것이 중요한 공정에 사용

**Comment by wns0394** [comment]
일괄처리
시분할
실시간

**Comment by CHOIJXWXN** [comment]
배치 / 시분할 / 실시간
시분할 많이 쓰는데 실시간도 늘어나는 추세
