### ISSUE TITLE
프로세스 A와 프로세스 B의 문맥 교환 과정을 서술하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#71]

**Comment by dudupeng3105** [comment]
시스템 콜 or 인터럽트 발생했을 때 문맥교환이라면, 이제 CPU 점유를 멈출 프로세스의 상태를 프로세스 PCB에 저장
그리고 새롭게 점유할 프로세스의 상태를 PCB에서 읽어옴

**Comment by hula-la** [comment]
프로세스 A에서 현재 어떤 코드를 진행하고 있었는지를 PC(program counter)에 저장하는 등 CPU에 대한 정보를 PCB에 저장하고,
프로세스 B에게 CPU 점유권을 준 후, B의 PCB를 읽어 이전의 작업을 이어감.

**Comment by kevin123488** [comment]
현재 프로세스의 정보를 pcb에 저장 -> cpu 새롭게 얻는 프로세스의 상태를 pcb에서 얻어옴

**Comment by bds01088** [comment]
프로세스에서 OS로 넘어갔다가 다시 원래 프로세스로 돌아오면 문맥 변경이 일어나지 않음
A프로세스에서 OS 갔다가 B 프로세스 가면 문맥 변환
A프로세스에서 OS로 변경되고 커널에 A프로세스의 pcb저장, B프로세스의 pcb 불러와서 cpu 할당?
