### ISSUE TITLE
DMA의 역할에 대해 서술하시오

### ISSUE THREAD

**Issue by hula-la** [mouseJAVA777/class_md#72]

**Comment by kevin123488** [comment]
빠른 입출력 장치를 메모리에 가까운 속도로 처리하기 위해 사용함

**Comment by mouseJAVA777** [comment]
인터페이스 장치에 제어권을 주어 직접 주기억장치와 데이터를 전송하는 방법(CPU와 계속적인 연결 X)

**Comment by ohhamin** [comment]
CPU에 I/O 장치가 입력될때마다 인터럽트 걸리면 손해가 크니깐 DMA가 블럭단위로 중간에서 처리하고 CPU에 보고함

**Comment by dudupeng3105** [comment]
CPU의 중재없이 디바이스 컨트롤러가 buffer의 내용을 메모리에 block 단위로 정송
block 단위로 인터럽트가 발생하기 때문에 CPU에 인터럽트가 걸리는 횟수가 적어져 효율적이다.

**Comment by nuriring** [comment]
하드웨어 하위 시스템이  CPU와 독립적으로 메인 시스템 메모리에 접근할 수 있게 해줌

**Comment by wns0394** [comment]
메모리에 CPU외에 접근 가능하게 만든다

**Comment by bds01088** [comment]
I/O 컨트롤러에서 직접 CPU로 인터럽트 걸면 너무 잦은 인터럽트로 인해 오버헤드가 심해짐으로
인터럽트를 모아서 CPU에 한번만 인터럽트를 보냄
