### ISSUE TITLE
Context switching 과정을 설명하시오.

### ISSUE THREAD

**Issue by hula-la** [mouseJAVA777/class_md#73]

**Comment by ohhamin** [comment]
타이머 인터럽트 요청이 오면 캐시 메모리같은거 PCB에 저장해 두고 문맥 교환해서 다음 프로세스 진행

**Comment by mouseJAVA777** [comment]
현재 진행중인 task의 상태를 진행하고 다음 task의 값을 읽어 적용 하는 과정

**Comment by kevin123488** [comment]
기존의 프로세스 상태를 저장해 둔 상태에서(PCB에) 새로운 프로세스의 상태를 갱신? 저장? 해주는것
