### ISSUE TITLE
DMA가 필요한 이유는?

### ISSUE THREAD

**Issue by nuriring** [mouseJAVA777/class_md#74]

**Comment by CHOIJXWXN** [comment]
CPU 바쁜데 자꾸 인터럽트 들어가면 효율이 안좋아서 적당히 IO 디바이스에서 들어오는 인터럽트를 DMA가 처리함
쟤가 메모리에 접근 가능해서 IO 장치가 로컬 버퍼에 저장해놓은 걸 CPU 대신 메모리에 복사해줌

**Comment by kevin123488** [comment]
빠른 입출력 장치를 메모리에 가까운 속도로 처리하기 위해

**Comment by hula-la** [comment]
고속의 I/O 장치의 경우 빈번한 인터럽트로 인해 CPU의 실제 프로세스 작업 시간이 감소하는데 이러한 문제를 해결하기 위한 컨트롤러

**Comment by mouseJAVA777** [comment]
키보드를 하나씩 타건할때마다 인터럽트가 발생한다면 오버헤드가 클 것, 이같은 현상 방지 목적

**Comment by dudupeng3105** [comment]
입출력 장치가 CPU의 처리 단위인 바이트 단위로 계속 인터럽트를 발생 시키면 CPU의 효율이 떨어지기 때문에, DMA가 IO장치의 buffer storage 안에 있는 걸 블록 단위로 메모리에 전송(이때만 인터럽트가 발생해서 전체 인터럽트 횟수가 줄어듬)
