### ISSUE TITLE
동기식 입출력과 비동기식 입출력의 차이는?

### ISSUE THREAD

**Issue by nuriring** [mouseJAVA777/class_md#75]

**Comment by kevin123488** [comment]
동기식 입출력: 입출력 요청 후 작업이 완료된 후에 제어가 사용자 프로그램으로 넘어감,
비동기식 입출력: 입출력 요청이 시작된 후 입출력 작업이 끝나기를 기다리지 않고, 제어가 사용자 프로그램으로 즉시 넘어감

**Comment by dudupeng3105** [comment]
중복입니다
