### ISSUE TITLE
문제: multilevel feedback queue의 scheduling에 대해 설명하라. (우선순위는 Q0>Q1>Q2, Q0 - time quantum 8ms, Q1 - time quantum 16 ms, Q2 - FCFS)

### ISSUE THREAD

**Issue by kevin123488** [mouseJAVA777/class_md#76]

**Comment by ohhamin** [comment]
큐를 여러개로 분할하여 스케쥴링을 한다. 각각의 큐는 다른 알고리즘을 가질 수 있고, 처음 프로세스가 들어오면 Q0에 들어갔다가 CPU 할당 후 두번 째 큐로 들어가는 식으로 스케쥴링이 진행된다.

**Comment by bds01088** [comment]
Q0에 순차적으로 들어가서 8초마다 CPU를 반납한다.
Q0에서 마무리 되지 못한 작업은 Q1로 들어가 16초의 작업시간을 통해 처리된다.
Q1에서도 마무리 되지 못한 작업들은 Q2에 선입선출로 처리된다.

**Comment by dudupeng3105** [comment]
만약에 새로운 작업이 Q0에 들어간다 Q0가 CPU를 할당받고, 8ms만큼 작업을 수행 후에 작업을 못 끝내면 Q1로 내려간다. Q1에서 기다리다가 CPU 할당받아서 16ms 작업 수행 후에도 못 끝내면 Q2로 들어가는데 Q2에서 기다리다가 Q1,Q0에 작업이 아무것도 없을 때야 Q2의 있는 작업을 FCFS스케줄링 방식으로 하나씩 처리된다.

**Comment by CHOIJXWXN** [comment]
일단 다 Q0로 들어감 라운드로빈으로 8ms씩 할당받고 그래도 아직 CPU가 필요하면 Q1으로 내려감
Q1은 보통 이전 큐보다 더 시간 넉넉하게 줌, 16ms 할당받고도 할 일 더 남았으면 Q2로 내려감
Q2는 선착순이므로 하나하나 들어온 순서대로 처리해나감
