### ISSUE TITLE
Copy-on-write(COW) 란 무엇인가?

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#77]

**Comment by hula-la** [comment]
부모 프로세스를 무지성 copy하면 메모리가 낭비될 수 있음.
최대한 똑같은건 공유하는게 효율적이므로, write(수정)할 때만 copy하도록 하는 것

**Comment by dudupeng3105** [comment]
처음부터 fork() - exit() 하는 식으로 copy하면 비효율적이라서, 리눅스 같은 경우에 그냥 PC만 카피해뒀다가 자식 프로세스가 write 실제로 하면 그 때 카피함

**Comment by CHOIJXWXN** [comment]
PC만 따로 두고 다른 자원은 다 공유하다가 부모랑 달라질 때만 카피
