### ISSUE TITLE
프로세스 스케줄링에서 프로그램 입장에서의 성능 척도 중 소요 시간, 대기 시간, 응답 시간에 대해 설명하시오

### ISSUE THREAD

**Issue by dudupeng3105** [mouseJAVA777/class_md#78]
소요시간:
대기시간:
응답시간:

**Comment by ohhamin** [comment]
이거 내가 내려고했는데 ㅋㅋ
소요시간 : CPU를 쓰러 들어와서 기다린 후 다 쓰고 나갈 때 까지의 시간
대기시간 : CPU를 쓰기 위해 기다린 시간(뺏기고 다시 기다린 시간도 합침)
응답시간 : 처음으로 CPU를 얻기까지 기다린 시간

**Comment by bds01088** [comment]
소요시간 : 프로세스가 진행되어서 마무리될때까지의 시간
응답시간 : 처음으로 대기줄에 들어와서 CPU를 받을때 까지 걸린 시간
대기시간 : CPU를 기다린 순수한 시간?

**Comment by hula-la** [comment]
소요시간: 음식집가서(**응답 요청한 후**) 음식 다 먹고 나올 때(**작업이 완전히 마무리됐을 때**)까지의 시간
대기시간: 코스요리 집에서(**응답을 요청했을 때**) 코스 음식들 기다리는데 걸리는 시간(**총 기다림 시간**)
응답시간: 자장면 집(**응답을 요청했을 때**)에서 단무지(**첫 응답**) 나오는 시간

**Comment by wns0394** [comment]
소요 시간 : CPU쓰러 들어와서 다 쓰고 나갈 때 까지 걸린 시간
대기 시간 : 기다리는 시간
응답 시간 : READY QUEUE 에 들어와서 처음으로 CPU를 얻기까지 걸린 시간

**Comment by CHOIJXWXN** [comment]
소요시간 : 대기시간 + 사용시간 (걍 들어갔다가 나오기까지 시간)
대기시간 : 레디큐에서 순수하게 기다린 시간
응답시간 : 레디큐에서 처음으로 CPU 차지하기까지 시간

**Comment by dudupeng3105** [comment]
[답지]
 - 소요 시간 (Turnaround Time) : 프로세스가 Ready queue에서 대기한 시간부터 작업을 완료하는데 걸리는 시간
 - 대기 시간 (Waiting Time) : 프로세스가 Ready queue에서 대기한 시간
 - 응답 시간 (Response Time) : 프로세스가 처음으로 CPU를 할당 받기까지 걸린 시간
