### ISSUE TITLE
critical-section이란?

### ISSUE THREAD

**Issue by ohhamin** [mouseJAVA777/class_md#79]

**Comment by dudupeng3105** [comment]
다수의 프로세스가 공유 데이터를 접근하는 "코드"

**Comment by bds01088** [comment]
병렬 처리하는데 있어서 여러 스레드가 동시에 접근하면 안되는 구역 -위키백과 참고-

**Comment by hula-la** [comment]
프로세스의 코드 중에서 공유 데이터에 접근하는 코드.
복수개의 프로세스가 critical-section에 접근하면 안됨~

**Comment by CHOIJXWXN** [comment]
공유데이터에 접근하는 코드

**Comment by wns0394** [comment]
공유 데이터를 접근하는 코드

**Comment by kevin123488** [comment]
공유 데이터를 접근하는 코드
