### ISSUE TITLE
MAC address란?

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#8]

**Comment by ohhamin** [comment]
물리적 주소 (16진수 앞에 6개는 제조 회사 뒤 6개는 제품 아이디)

**Comment by dudupeng3105** [comment]
컴퓨터의 물리적 주소 앞의 3바이트는 제조사, 뒤의 3바이트는 제품 아이디

**Comment by kevin123488** [comment]
물리적 주소(식별 Id + 고유번호)

**Comment by nuriring** [comment]
물리적주소를 의미함(식별 아이디+고유번호)

**Comment by bds01088** [comment]
해당 노드(기기)의 물리적 주소

**Comment by CHOIJXWXN** [comment]
장치의 물리적 주소로, 16진수 12개로 이루어져있다. 앞의 3바이트는 OUI, 뒤의 3바이트는 제조사에서 준 고유번호이다.

**Comment by hula-la** [comment]
물리적 주소
앞 24비트는 제조업체 식별코드
뒤 24비트는 고유코드
