### ISSUE TITLE
문제: Algorithm evaluation의 방법 3가지는?

### ISSUE THREAD

**Issue by kevin123488** [mouseJAVA777/class_md#80]

**Comment by ohhamin** [comment]
시뮬레이션이랑,,, 이론적으로 하는거랑,,,,,,, 하나가 더 있긴 함

**Comment by dudupeng3105** [comment]
음 시뮬레이션, 실제 작업에 대해서 하는거, 식으로 하는 거?

**Comment by hula-la** [comment]
시뮬레이션, 실제 돌리는거, +1 (자세한건 기억이 안남)

**Comment by CHOIJXWXN** [comment]
이론 실측 시뮬레이션

**Comment by kevin123488** [comment]
[답]
queueing models -> 큐에 job이 도착 -> 도착한 프로세스들을 cpu 능력에 따라 처리 후 빠져나가는 service rate 등을 통해 performance index 값을 계산. 요즘 실제로는 많이 쓰지 않음

Implementation & Measurement -> 실제로 구현해서 돌려본 후 성능 측정

Simulation -> 알고리즘을 모의 프로그램으로 작성 후 trace를 입력으로 하여 결과 비교. trace? 시뮬레이션 프로그램에 input으로 들어갈 데이터
