### ISSUE TITLE
멀티레벨큐(Multilevel Queue)와 멀티레벨 피드백큐(Multilevel Feedback Queue)의 차이점을 설명하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#82]

**Comment by ohhamin** [comment]
멀티레벨큐는 우선순위가 높은 큐가 비었을 때만 다음 큐에 CPU가 할당되어서 starvation 현상이 발생할 수 있는데 멀티레벨 피드백큐는 큐간 이동이 가능하여 좋다~

**Comment by dudupeng3105** [comment]
멀티레벨큐는 해당 큐에 들어가게되면 다른 큐로 이동할 수가 없음 계층 간의 이동이 없음. 그래서 I/O 작업 같은 우선순위가 높은 큐의 작업이 많으면 그것만 하다가 계산 위주의 우선순위가 낮은 작업이 있는 큐는 처리되지 못하는 기아현상 발생
-> 이를 해결하기 위해 계층 간 이동이 가능한 멀티레벨피드백 큐 구형

**Comment by kevin123488** [comment]
프로세스가 다른 큐로 이동할 수 있는지 없는지의 차이

**Comment by bds01088** [comment]
멀티레벨큐는 계층이동이 불가능하고
멀티레벨 피드백큐는 말그대로 피드백을 해줘서 계층이동이 가능하게 함으로써 starvation을 줄일 수 있다.

**Comment by wns0394** [comment]
멀티레벨 큐는 다른 큐로 이동 불가능
멀리레벨 피드백 큐는 프로세스가 다른 큐로 이동 가능
