### ISSUE TITLE
프로그램이 비자발적으로 종료되는 경우의 예시를 두 개 이상 서술하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#83]

**Comment by ohhamin** [comment]
사용자가 종료함, 부모가 종료됨

**Comment by dudupeng3105** [comment]
부모가 마음에 안 들어서 종료시킴(자식이 리소스를 너무 많이 먹거나, 자식이 이제 필요없다고 판단될 때 등), 부모가 사라져버림(자식도 사라짐)

**Comment by bds01088** [comment]
1) 자식 프로세스가 할당 자원의 한계치를 넘어서 사용한 경우
2) 자식에게 할당된 테스크가 더 이상 필요하지 않은 경우
3) 부모 프로세스가 종료(exit)하는 경우
-구글링-

**Comment by wns0394** [comment]
부모가 종료

**Comment by kevin123488** [comment]
자식이 더이상 쓸데가 없을 때, 자식이 자원 많이 쓰는 것 같을 때

**Comment by CHOIJXWXN** [comment]
1. 자식 프로세스가 한계치를 넘어서는 자원을 요청
2. 자식 프로세스에 할당된 태스크가 불필요
3. 사용자 명령
4. 부모 프로세스의 종료
