### ISSUE TITLE
콘보이 현상(Convoy effect)이란 무엇이고, 콘보이 현상이 발생될 수 있는 CPU 스케줄러 알고리즘은 무엇인지 설명하시오.

### ISSUE THREAD

**Issue by hula-la** [mouseJAVA777/class_md#84]

**Comment by wns0394** [comment]
앞에 프로세스가 cpu 사용 시간이 엄청 크다면 다른 프로세스가 많은 시간 기다리는 현상 FCFS방식에서 많이 발생한다.

**Comment by CHOIJXWXN** [comment]
FCFS(선착순) 방식을 채택할 때 나타나는 현상으로, CPU Burst Time이 긴 프로세스가 먼저 도착한다면 CPU Burst Time이 짧은 프로세스들이 지나치게 오래 기다려야 하는 현상을 의미한다.

**Comment by dudupeng3105** [comment]
FCFS, 긴 놈이 혼자 계속 점유해서 다른 놈들이 오래 기다려야함

**Comment by bds01088** [comment]
콘보이 현상이란
가장 먼저 도착한 프로세스가 가장 긴 CPU사용시간을 가지고 있어서 뒤에 오는 CPU사용시간이 짧은 프로세스들이 모두 정체되는 현상이다.
비선점형 스케줄링에 자주 나타난다.

**Comment by hula-la** [comment]
[답지]
콘보이 현상이란 작업 시간의 긴 프로세스가 먼저 큐에 도착해서 다른 프로세스의 실행 시간이 전부 늦춰져 효율성을 떨어뜨리는 현상을 말함.
FCFS 스케줄링은 비선점형으로, 순차적으로 먼저 큐에 들어온 작업부터 실행하므로 콘보이 현상이 발생할 수 있음.
