### ISSUE TITLE
FCFS(FIRST-COME-FIRST-SERVED) 방식은 비효율적인데 장점과 사용 예시는?

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#85]

**Comment by ohhamin** [comment]
장점 : 장점이 있나,,? 간단하다.
사용예시 : 멀티레벨 피드백큐에서 마지막 큐는 FCFS로 사용. 현실에서 사용

**Comment by dudupeng3105** [comment]
장점 : 장점이라면 context switch가 빈번하지 않기 때문에 I/O bound 작업이 적고 CPU bound 작업이 많은 경우 유리할 수 있다. (모르겠음), 구현도 쉬움
단점 : 간단한 시스템

**Comment by bds01088** [comment]
장점 : context switch가 적어서 오버헤드가 발생하지않는다..?
사용 예시 : starvation을 해결해준다..?

**Comment by kevin123488** [comment]
장점: 비선점이라 할당된 도중 끊기지 않는다? 모르겠음
사용처: 어디쓰냐

**Comment by wns0394** [comment]
자원의 효율성을 높임(처리중인 프로세스에게 할당된 시간을 타 프로세스가 뺏지 않으므로 문맥 교환이 일어나지 않음, 오버헤드 발생x)

일괄 처리 시스템에 적합함

 멀티레벨 피드백큐에서 마지막 큐에 사용
