### ISSUE TITLE
선점형 스케줄링과 비선점형 스케줄링의 차이를 설명해주시오.

### ISSUE THREAD

**Issue by hula-la** [mouseJAVA777/class_md#86]

**Comment by wns0394** [comment]
선점형 : cpu 줘도 더 짧은 cpu 사용하는 프로세스가 나타나면 그 프로세스에게 cpu를 줌 (줬다가 뺏음)
비선점형 : 기다리는 프로세스 중 가장 짧은 사용시간을 가진 프로세스에게 cpu를 줌 더 짧은 프로세스가 와도 기다려야 함 (줬다 못뺏음)

**Comment by CHOIJXWXN** [comment]
선점형 : A 프로세스가 CPU 사용하고 있는 중에도 더 우선순위가 높은 프로세스 B가 들어오면 프로세스 B에게 CPU 할당
비선점형 : 그런 거 없고 A가 다 쓰고난 다음 우선순위 높은 애로 넘어감

**Comment by kevin123488** [comment]
선점형: 다른 프로세스가 cpu를 사용하고 있어도 또다른 프로세스가 해당 cpu를 할당받을 수 있음
비선점형: cpu 사용중인 프로세스가 종료되어야 다른 프로세스가 cpu 할당받기 가능

**Comment by dudupeng3105** [comment]
선점형: 운영체제가 프로세스의 사용권 통제(운영체제가 우선 순위 높은 놈을 CPU 할당하고 싶으면 할당시켜버림)
비선점형: 프로세스가 스스로 넘겨줘야함(안 비켜줌)

**Comment by ohhamin** [comment]
그게맞음

**Comment by bds01088** [comment]
선점형 : 스케줄링에 따라서 CPU를 다른 프로세스가 중간에 가져올 수 있음
비선점형 : 한번 받은 CPU는 자기 일 끝날때까지 다 처리하고 나서 넘겨줌

**Comment by hula-la** [comment]
[답지]
선점형: 하나의 프로세스가 다른 프로세스 대신에 CPU를 차지할 수 있음
비선점형: 하나의 프로세스가 끝나지 않으면 다른 프로세스는 CPU를 사용할 수 없음
