### ISSUE TITLE
SJF(Shortest-job-first) : CPU를 사용하고자 하는 시간이 가장 짧은 프로그램에서 CPU를 주는 방식인데 이방식의 단점은 무엇인가? 그리고 단점을 해결하기위한 방법은?

### ISSUE THREAD

**Issue by wns0394** [mouseJAVA777/class_md#87]

**Comment by CHOIJXWXN** [comment]
CPU burst time이 긴 애들은 CPU 영원히 못쓰는 수가 있음 그래서 선착순으로 하든가 기다린 만큼의 우선순위를 주는 걸로 해결

**Comment by dudupeng3105** [comment]
CPU burst time이 긴 애들 계속 뒤로 밀림, 에이징 같이 기다린 시간 길어지면 우선순위가 올라가는 식으로 해결할 수 있음

**Comment by ohhamin** [comment]
시간이 길면 디져도 못씀(starvation), 시간이 지나면 우선순위를 높여줌

**Comment by hula-la** [comment]
burst time이 긴 애들은 CPU를 계속 받을 수 없는 starvation이 발생할 수 있음.
뒤로 밀려나는 만큼 우선순위를 높여줌

**Comment by kevin123488** [comment]
시간이 긴 애들은 사용하지 못하는 문제점을 기다린 시간에 따른 우선순위 상승으로 해결 가능

**Comment by bds01088** [comment]
CPU 사용 시간이 긴 애들은 계속 뒤로 밀려서 처리가 아예 안되는 경우가 발생함
시간을 설정하여서 일정시간마다 계속 돌아가면서 사용되도록 한다

**Comment by wns0394** [comment]
starvation(기아 현상)

해결 방안으로는 aging기법(아무리 우선순위가 높아도 시간이 지남에따라 우선순위를 줄여줌)이 있다.
