### ISSUE TITLE
semaphore에 대해서 설명하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#88]

**Comment by dudupeng3105** [comment]
Busy Waiting이 필요 없는 동기화 도구, 여러 프로세스나 스레드가 Critical Section에 진입할 수 있는 Signaling 메커니즘

**Comment by mouseJAVA777** [comment]
세마포어 : 추상화
sychronization 문제를 P(자원획득) V(자원반납) 두 가지 연산을 통해 자원에 접근 가능

**Comment by nuriring** [comment]
공유된 자원의 데이터 혹은 임계영역(Critical Section) 등에 여러 Process 혹은 Thread가 접근하는 것을 제한하는 방법

**Comment by bds01088** [comment]
하드웨어에서 두가지 작업을 atomic하게 처리해주는 방식을 추상화하여 나타내어 표기한 것

**Comment by CHOIJXWXN** [comment]
정답 예시 : 
정수형 변수와 P연산, V연산을 포함한 추상자료형
P연산은 공유 데이터를 획득하는 연산, V연산은 공유 데이터를 반납하는 연산을 의미
