### ISSUE TITLE
Monitor 와 Semaphore 의 차이점

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#89]

**Comment by CHOIJXWXN** [comment]
세마포어는 실수 한 번 하면 치명적임 그래서 모니터를 씀
모니터는 내부에 정의된 연산이 있음
얘를 써야만 공유데이터에 접근할 수가 있는데 그래서 원천적으로 여러 프로시져가 동시에 실행될 수 없게 막아 놓음
우리가 Lock을 걸 필요가 없어짐

**Comment by dudupeng3105** [comment]
모니터는 락을 걸 필요가 없음, 그래서 프로그래머가 작성할 때 실수를 크게 걱정하지 않아도 됨

**Comment by bds01088** [comment]
락이 없음
