### ISSUE TITLE
2계층 이더넷 헤더에는 어떤 정보들이 포함되어야 하는가?

### ISSUE THREAD

**Issue by hula-la** [mouseJAVA777/class_md#9]

**Comment by ohhamin** [comment]
송신 어드레스, 수신 어드레스, 다음 프로토콜 정보

**Comment by dudupeng3105** [comment]
destination address(6바이트), source address(6바이트), ethernet type(2바이트) 이다.

**Comment by nuriring** [comment]
목적지 주소 (6)+ 보낸 주소(6) + 이더넷 타입(2)에는 상위 프로토콜에 대한 정보가 담겨 있습니다.

**Comment by mouseJAVA777** [comment]
목적지 맥 주소 / 출발지 맥주소 / 이더넷 타입

**Comment by bds01088** [comment]
도착지 맥 주소 6바이트, 출발지 맥 주소 6바이트, 이더넷 타입 2바이트, 데이터

**Comment by kevin123488** [comment]
Destination Address + Source Address + Ethernet Type

**Comment by CHOIJXWXN** [comment]
Destination Address 6바이트와 Source Address 6바이트, 그리고 Ethernet Type 2바이트로 이루어져있다. Destination Address는 목적지 주소, Source Address는 보내는 사람 주소, Ethernet Type은 상위 프로토콜의 미리보기이다.
