### ISSUE TITLE
식사하는 철학자 문제의 해결법을 아는 만큼 제시하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#90]

**Comment by mouseJAVA777** [comment]
1. 비대칭으로 한다 (짝수는 왼쪽먼저잡고 홀수는 오른쪽 먼저잡는 식)
2. 두 개 다 집을 수 있을 때 집게한다
3.  빈자리를 둔다

**Comment by dudupeng3105** [comment]
그 뭐냐.. 양 옆 사람이 밥을 안 먹을 때 젓가락을 가져갈 권한을 주는 방법

**Comment by nuriring** [comment]
한 철학자가 젓가락 두개를 모두 집을 수 있을 때만 젓가락을 집도록 허용

**Comment by CHOIJXWXN** [comment]
정답 예시 : 
1. 젓가락을 들고자 하는 철학자만이 테이블에 앉으며 테이블에는 동시에 N - 1명 이하만 앉을 수 있도록
2. 양쪽 젓가락을 모두 집을 수 있을 때만 젓가락을 잡도록
3. 비대칭 (왼쪽 오른쪽 번갈아 먼저 집도록, 예를 들면 1번 철학자는 왼쪽, 2번 철학자는 오른쪽)
