### ISSUE TITLE
데드락의 조건에 대해서 서술하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#91]

**Comment by mouseJAVA777** [comment]
1. 강제로 뺏기지 않음
2. 프로세스간 자원을 기다리는 사이클을 형성함
3. 다른 자원을 기다릴 때 내 자원을 놓지않음
4. 하나뭐지ㅋㅋ

**Comment by dudupeng3105** [comment]
4. mutual exclusion - 매 순간 하나의 프로세스만 자원을 사용 가능

**Comment by bds01088** [comment]
1. 자기 자원 들고 대기
2. 자원을 뺏기지 않음
3. 사이클 형성함
4. 매 순간 하나의 프로세스가 자원을 가짐

**Comment by nuriring** [comment]
1. Mutual exclusion (상호 배제)
2. Hold and wait (보유 대기)
3.  No preemption (비선점)
4. Circular wait (순환 대기)

**Comment by CHOIJXWXN** [comment]
정답 예시 : 
1. Mutual Exclusion (상호 배제) : 매 순간 하나의 프로세스만이 자원을 사용할 수 있음
2. No Preemption (비선점) : 프로세스는 자원을 스스로 내어놓을 뿐 빼앗기지 않음
3. Hold and Wait (보유 대기) : 자원을 가진 프로세스가 다른 자원을 기다릴 때 보유 자원을 놓지 않고 계속 가지고 있음
4. Circular Wait (순환 대기) : 자원을 기다리는 프로세스간에 사이클이 형성되어야 함
