### ISSUE TITLE
Deadlock 처리방법 4가지

### ISSUE THREAD

**Issue by mouseJAVA777** [mouseJAVA777/class_md#92]

**Comment by CHOIJXWXN** [comment]
Prevention, Avoidance, Detection & Recovery, Ignorance
Prevention이랑 Avoidance는 미연에 방지하는 방법이고 가장 강력함
그치만 효율성의 문제로 보통 Ignorance 채택

**Comment by dudupeng3105** [comment]
prevention, avoidance, detection and recovery, Ignorance

**Comment by bds01088** [comment]
예방, 회피, 발견&해결, 무시

**Comment by nuriring** [comment]
prevention, avoidance, detection and recovery, Ignorance
