### ISSUE TITLE
Banker's Algorithm에 대해 간략하게 설명하세요

### ISSUE THREAD

**Issue by CHOIJXWXN** [mouseJAVA777/class_md#93]

**Comment by mouseJAVA777** [comment]
현재 available에 자원들이 있더라도 한 프로세스의 Need(최대로 요구할 수 있는 자원들)를 충족시키지 못한다면 자원을 조금이라도 내주지 않음. 따라서 비효율적이지만 deadlock을 막을 수 있음

**Comment by dudupeng3105** [comment]
총 요청 자원의 수가 남은 자원의 수보다 적은 프로세스만 선택하여 수행함

**Comment by bds01088** [comment]
해당 프로세스가 자원을 요청할 때
최대 요청할 수 있는 자원과 현재 사용가능한 자원을 비교하여 해당 프로세스가 작업이 완료가 될 수 있다면
자원을 제공하고
작업이 불가능하다면 요청한 자원의 수가 최대 요청 자원의 수보다 작아도 주지 않음

**Comment by nuriring** [comment]
할당받은 프로세스가 종료되면 모든 자원을 반납함, 모든 프로세스가 종료될 때가지 이 과정을 반복함

**Comment by CHOIJXWXN** [comment]
정답 예시 : 
!! 다익스트라를 만든 사람이 만들었다고 함
안전 상태를 유지할 수 있는 요구만을 수락하고 불안전 상태를 초래하는 사용자의 요구는 나중에 만족될 수 있을 때까지 계속 거절

안전 상태 : 프로세스가 요구한 최대 요구량만큼 필요한 자원을 할당해줄 수 있는 상태로 안전순서열이 존재하는 상태
불안전 상태 : 안전순서열이 존재하지 않는 상태, 교착 상태의 필요 조건

안전 상태와 불안전 상태를 판별하기 위해 필요한 값은 Max, Allocation, Available

Max : 프로세스가 자원을 얼마나 요청할 수 있는지
Allocation : 현재 프로세스가 자원을 얼마나 보유하고 있는지
Available : 시스템이 자원을 얼마나 보유하고 있는지
Need = Max - Allocation
