### ISSUE TITLE
Spin lock이 무엇인가요?

### ISSUE THREAD

**Issue by dudupeng3105** [mouseJAVA777/class_md#94]

**Comment by mouseJAVA777** [comment]
CPU를 점유하고 있을 때 공유 자원을 사용해도 되는지 While문을 통해 계속 확인함

**Comment by nuriring** [comment]
만약 다른 스레드가 lock을 소유하고 있다면 그 lock이 반환될 때까지 계속 확인하며 기다리는 것

**Comment by bds01088** [comment]
busy waiting의 다른말로
자원을 받을때까지 계속 해당 조건을 확인하는 작업을 진행하기 때문에 cpu와 렘을 차지하는 현상

**Comment by dudupeng3105** [comment]
[답지]lock이 반환될 때까지 계속 확인하면서 프로세스가 기다리는 것을 다른 용어로 Spin Lock이라고 한다. 

Spin Lock은 Critical Section에 진입을 위한 대기 시간이 짧을 때, 즉 Context Switching 하는 비용보다 기다리는 게 더 효율적인 특수한 상황을 위해 고안된 것이다. 단일 CPU 시스템에서는 어차피 Lock을 갖고 있는 스레드를 풀어주기 위해서 Context Switching이 일어나야 하기 때문에 유용하지 않고, 멀티 프로세서 시스템에서 종종 사용된다.
