### ISSUE TITLE
세마포어에 어떤 메커니즘인가요?

### ISSUE THREAD

**Issue by dudupeng3105** [mouseJAVA777/class_md#95]

**Comment by nuriring** [comment]
세마포어는 동기화를 위해 wait와 signal이라는 2개의 atomic operations를 사용한다.
wait를 호출하면 세마포어의 카운트를 1줄이고, 세마포어의 카운트가 0보다 작거나 같아질 경우에 락이 실행된다. 

by  구글선생님

**Comment by bds01088** [comment]
하드웨어에서 제공하는 기술을 통해
두개의 처리작업을 하나의 처리작업으로 진행하는 것을 추상화하는것?

**Comment by dudupeng3105** [comment]
[답지]
세마포어(Semaphore)는 Busy Waiting이 필요 없는 동기화 도구이며, 여러 프로세스나 스레드가 Critical Section에 진입할 수 있는 Signaling 메커니즘이다.
