### ISSUE TITLE
Deadlock prevention의 단점을 서술하시오

### ISSUE THREAD

**Issue by nuriring** [mouseJAVA777/class_md#96]

**Comment by dudupeng3105** [comment]
예방하는데 들이는 리소스 때문에 효율성과 처리량 감소되고, starvation 발생 가능

**Comment by CHOIJXWXN** [comment]
데드락이 자주 발생하는 애가 아닌데 이거 막으려고 오버헤드를 감수해야한다? 비효율적임
그리고 데드락 해결하려다가 기아 생길 수 있음

**Comment by mouseJAVA777** [comment]
ㅇㅈ 개비효율적 그냥 냅두고 사용자가 처리하는게 맞다

**Comment by bds01088** [comment]
그렇군요
