### ISSUE TITLE
여러 프로세스의 동시접속을 막기 위한 프로그램적 해결법의 충족 조건 세가지를 쓰시오

### ISSUE THREAD

**Issue by bds01088** [mouseJAVA777/class_md#97]

**Comment by dudupeng3105** [comment]
Mutual Exclusion, Progress, Bounded Waiting

**Comment by mouseJAVA777** [comment]
동의합니다
1. 누가 critical section에 있으면 들어가면 안댐
2. 아무도 없을 때 들어갈 수 있어야댐
3. stavation 막기 위해 내가 요청하면 다른 프로세스들의 횟수 제한이 있어야댐

**Comment by nuriring** [comment]
- Mutual Exclusion : 프로세스가 임계영역을 수행중이면 다른 프로세스는 못들어옴
- Progress : 아무도 임계영역에 없으면 들어가고자 하는 프로세스 허용해줘야함
- Bounded Waiting: 다른 프로세스가 임계영역에 들어오고자 하는 요청과 요청 허용 사이 횟수 제한이 필요함

: 프로세스 Pi가 critical section 부분을 수행 중이면 다른 모든 프로세스들은 그들의 critical section에 들어가면 안 된다.
- Progress
: 아무도 critical section에 있지 않은 상태에서 critical section에 들어가고자 하는 프로세스가 있으면 critical section에 들어가게 해주어야 한다.
- Bounded Waiting
: 프로세스가 critical section에 들어가려고 요청한 후부터 그 요청이 허용될 때까지 다른 프로세스들이 critical section에 들어가는 횟수에 한계가 있어야 한다.

**Comment by CHOIJXWXN** [comment]
이하 동문
