### ISSUE TITLE
Banker's Algorithm 의 가정을 서술하시오

### ISSUE THREAD

**Issue by nuriring** [mouseJAVA777/class_md#98]

**Comment by dudupeng3105** [comment]
1. 모든 프로세스의 자원의 최대 사용량을 알아야함
2. 프로세스가 요청 자원을 할당 받은 후 일정 시간 안에 자원들을 다시 반납

**Comment by bds01088** [comment]
최대 자원 사용량을 알고
현재 자원 사용 가능량이 있고
해당 프로세스의 최대 자원 사용량이 현재 자원 사용 가능량보다 크다면,
자원 요청 무시함
모든 프로세스가 해결되는 시퀀스가 존재하면 데드락이 없다는 뜻
